Repository cloudquery/plugin-sdk, pull requests merged in 2022-09, with the labels that each got.

#41 feat: Remove Unique constraint (support pks only)
  plugins/source.go
  schema/column.go
  schema/meta.go
Labels: feat

#11 fix: Pointers to slice are handled correctly
  helpers/slice.go
  helpers/slice_test.go
Labels: fix

#29 feat: Add Name() to source and destination clients
  clients/destination.go
  clients/source.go
  internal/pb/base.pb.go
  internal/pb/base.proto
  internal/pb/destination.pb.go
  internal/pb/destination.proto
  internal/pb/destination_grpc.pb.go
  internal/pb/source.pb.go
  internal/pb/source.proto
  internal/pb/source_grpc.pb.go
  internal/servers/destinations.go
  internal/servers/source.go
  plugins/source.go
  plugins/source_test.go
Labels: feat

#46 feat: Add PreResourceResolver to accommodate list/detail pattern
  codegen/golang.go
  codegen/table.go
  codegen/templates/table.go.tpl
  schema/resource.go
  schema/table.go
Labels: feat

#49 fix!: Logger wasnt passed to source plugin resulting no errors
  plugins/source.go
  plugins/source_test.go
  schema/table.go
  serve/serve_test.go
Labels: fix, breaking

#52 feat: Add custom faker
  codegen/golang.go
  faker/faker.go
  faker/faker_test.go
  plugins/source.go
  plugins/source_testing.go
Labels: feat

#54 feat: Add sentry for serve.Serve function
  go.mod
  go.sum
  plugins/source.go
  schema/table.go
  serve/serve.go
Labels: feat

#47 feat: Generate source plugin docs
  docs/source.go
  docs/source_test.go
  schema/md_docs.go
  schema/md_docs_test.go
  serve/doc.go
Labels: feat

#57 feat!: Remove unused table create options
  codegen/table.go
  schema/table.go
Labels: automerge, feat, breaking

#56 fix: Ignore hidden files
  specs/spec_reader.go
Labels: fix

#60 feat: Remove IgnoreError and send sentry only on panics
  plugins/source.go
  schema/table.go
  serve/serve.go
Labels: feat

#59 feat: Make logs consistent
  schema/table.go
Labels: automerge, feat

#66 chore(deps): Update tubone24/update_release digest to a82eaa1
  .github/workflows/release-pr.yml
Labels: ignore-for-release

#64 chore: Golangci: remove deprecated plugins (and decorder)
  .golangci.yml
Labels: ignore-for-release

#61 feat: Generate full example configs from within SDK
  clients/destination.go
  clients/source.go
  codegen/doc.go
  docs/source_test.go
  internal/pb/base.pb.go
  internal/pb/base.proto
  internal/pb/destination.pb.go
  internal/pb/destination.proto
  internal/pb/destination_grpc.pb.go
  internal/pb/source.pb.go
  internal/pb/source.proto
  internal/pb/source_grpc.pb.go
  internal/servers/destinations.go
  internal/servers/source.go
  plugins/destination.go
  plugins/destination_test.go
  plugins/source.go
  plugins/source_docs.go
  plugins/source_test.go
  plugins/templates/destination.go.tpl
  plugins/templates/source.go.tpl
  schema/resource_test.go
  schema/table.go
  serve/serve.go
  serve/serve_test.go
  specs/spec_reader.go
Labels: feat

#70 feat: Revert "feat: Generate full example configs from within SDK"
  clients/destination.go
  clients/source.go
  codegen/doc.go
  docs/source_test.go
  internal/pb/base.pb.go
  internal/pb/base.proto
  internal/pb/destination.pb.go
  internal/pb/destination.proto
  internal/pb/destination_grpc.pb.go
  internal/pb/source.pb.go
  internal/pb/source.proto
  internal/pb/source_grpc.pb.go
  internal/servers/destinations.go
  internal/servers/source.go
  plugins/destination.go
  plugins/destination_test.go
  plugins/source.go
  plugins/source_docs.go
  plugins/source_test.go
  plugins/templates/destination.go.tpl
  plugins/templates/source.go.tpl
  schema/resoruce_test.go
  schema/table.go
  serve/serve.go
  serve/serve_test.go
  specs/spec_reader.go
Labels: automerge, feat

#72 fix: Fix typo in GetDestinationByName
  specs/spec_reader.go
Labels: fix

#74 chore: Upgrade to Go 1.19
  .github/workflows/lint_golang.yml
  .github/workflows/unittest.yml
  codegen/doc.go
  docs/source_test.go
  go.mod
  schema/table.go
  specs/spec_reader.go
Labels: ignore-for-release

#78 fix: Add missing comma when generating relations
  codegen/.snapshots/TestGenerateTemplate-should_add_comma_between_relations
  codegen/golang_test.go
  codegen/templates/table.go.tpl
  go.mod
  go.sum
Labels: fix

#86 feat!: Depracate override columns
  codegen/golang.go
  codegen/table.go
Labels: feat, breaking

#89 fix!: Enable export lin rule and fix option export
  .golangci.yml
  faker/faker.go
Labels: automerge, fix, breaking

#95 feat: Add PostResourceResolver to template
  codegen/templates/table.go.tpl
Labels: feat

#92 fix: Remove description from docs
  docs/.snapshots/TestGenerateSourcePluginDocs-relation_table.md
  docs/.snapshots/TestGenerateSourcePluginDocs-test_table.md
  docs/source.go
  docs/source_test.go
Labels: automerge, fix

#96 feat!: Disable default completion command
  serve/serve.go
Labels: automerge, feat, breaking

#90 fix: Remove empty test and enable some lint rules
  .golangci.yml
  schema/resoruce_test.go
Labels: automerge, fix

#88 fix!: Enable var names lint rule and fix issues
  .golangci.yml
  faker/faker.go
  plugins/source.go
  schema/filters.go
  schema/meta.go
  schema/resolvers.go
  schema/resource.go
  specs/spec.go
Labels: automerge, fix, breaking

#85 fix(testing): Validate all tables and relations
  plugins/source_testing.go
Labels: automerge, fix

#100 fix: Remove old entries from changelog
  CHANGELOG.md
Labels: automerge, fix

#105 chore(makefile): Install protoc dependecies
  Makefile
Labels: ignore-for-release

#108 feat: Remove withComment for codegen
  codegen/golang.go
  codegen/table.go
Labels: feat

#111 feat: Add minor improvements to WithUnwrap codegen options
  codegen/golang.go
  codegen/golang_test.go
  codegen/table.go
Labels: feat

#106 chore(refactor): Make `interpolateAllResources` more readable
  plugins/source.go
  plugins/source_test.go
Labels: automerge, ignore-for-release

#115 fix: Improve error message on codegen field error
  codegen/golang.go
Labels: fix

#120 feat: Add GetDestinations function to list all destinations
  specs/spec_reader.go
Labels: automerge, feat

#118 chore(docs): Add more godoc to important APIs
  README.md
  clients/doc.go
  clients/source.go
  codegen/doc.go
  codegen/golang.go
  plugins/docs.go
  plugins/source.go
  schema/doc.go
  serve/doc.go
  specs/doc.go
  specs/source.go
Labels: automerge, ignore-for-release

#119 chore(ci): Lint markdown files
  .github/styles/Vocab/Base/accept.txt
  .github/styles/Vocab/Base/reject.txt
  .github/styles/proselint/Airlinese.yml
  .github/styles/proselint/AnimalLabels.yml
  .github/styles/proselint/Annotations.yml
  .github/styles/proselint/Apologizing.yml
  .github/styles/proselint/Archaisms.yml
  .github/styles/proselint/But.yml
  .github/styles/proselint/Cliches.yml
  .github/styles/proselint/CorporateSpeak.yml
  .github/styles/proselint/Currency.yml
  .github/styles/proselint/Cursing.yml
  .github/styles/proselint/DateCase.yml
  .github/styles/proselint/DateMidnight.yml
  .github/styles/proselint/DateRedundancy.yml
  .github/styles/proselint/DateSpacing.yml
  .github/styles/proselint/DenizenLabels.yml
  .github/styles/proselint/Diacritical.yml
  .github/styles/proselint/GenderBias.yml
  .github/styles/proselint/GroupTerms.yml
  .github/styles/proselint/Hedging.yml
  .github/styles/proselint/Hyperbole.yml
  .github/styles/proselint/Jargon.yml
  .github/styles/proselint/LGBTOffensive.yml
  .github/styles/proselint/LGBTTerms.yml
  .github/styles/proselint/Malapropisms.yml
  .github/styles/proselint/Needless.yml
  .github/styles/proselint/Nonwords.yml
  .github/styles/proselint/Oxymorons.yml
  .github/styles/proselint/P-Value.yml
  .github/styles/proselint/RASSyndrome.yml
  .github/styles/proselint/README.md
  .github/styles/proselint/Skunked.yml
  .github/styles/proselint/Spelling.yml
  .github/styles/proselint/Typography.yml
  .github/styles/proselint/Uncomparables.yml
  .github/styles/proselint/Very.yml
  .github/styles/proselint/meta.json
  .github/workflows/lint_markdown.yml
  .markdownlint.yaml
  .vale.ini
  CONTRIBUTING.md
  README.md
Labels: automerge, ignore-for-release

#124 feat: Make GenerateSourcePluginDocs struct method
  docs/source.go
  plugins/.snapshots/TestGenerateSourcePluginDocs-README.md
  plugins/.snapshots/TestGenerateSourcePluginDocs-relation_table.md
  plugins/.snapshots/TestGenerateSourcePluginDocs-test_table.md
  plugins/source_docs.go
  plugins/source_docs_test.go
  serve/doc.go
Labels: feat

#126 feat!: Idiomatic serve interface
  serve/destination.go
  serve/doc.go
  serve/serve.go
  serve/source.go
  serve/source_test.go
Labels: feat, breaking

#112 feat: Use JSON tag for column name if applicable
  codegen/golang.go
  codegen/golang_test.go
  codegen/table.go
Labels: automerge, feat

#110 test: Bring back `spec_reader` tests
  specs/spec_reader_test.go
  specs/spec_test.go
  specs/testdata/aws.yml
  specs/testdata/postgresql.yml
Labels: automerge, test

#127 feat: Add version flag
  serve/destination.go
  serve/source.go
Labels: automerge, feat

#131 feat: Add Multiplexer function type
  schema/table.go
Labels: feat

#129 fix: Bring concurrency back
  plugins/source.go
  specs/source.go
  specs/spec_reader_test.go
  specs/spec_test.go
  specs/testdata/aws.yml
Labels: fix

#136 feat: Add PK information to generated docs
  plugins/.snapshots/TestGenerateSourcePluginDocs-relation_table.md
  plugins/.snapshots/TestGenerateSourcePluginDocs-test_table.md
  plugins/source_docs.go
  plugins/source_docs_test.go
Labels: automerge, feat

#137 fix: Skip fields that have "-" json tag
  codegen/golang.go
  codegen/golang_test.go
Labels: fix

#144 feat: Validate undefined column in TestResource
  plugins/source_testing.go
Labels: feat

#146 fix: Use plugin name to print usage
  serve/destination.go
  serve/source.go
Labels: automerge, fix

#142 feat: Add information about relations to generated docs
  plugins/.snapshots/TestGenerateSourcePluginDocs-README.md
  plugins/.snapshots/TestGenerateSourcePluginDocs-relation_table.md
  plugins/.snapshots/TestGenerateSourcePluginDocs-test_table.md
  plugins/source.go
  plugins/source_docs.go
  plugins/templates/all_tables.go.tpl
  plugins/templates/table.go.tpl
Labels: automerge, feat

#151 feat: Make default transformer exported to use in custom transformers
  codegen/golang.go
  codegen/golang_test.go
Labels: feat

#153 feat: Add support for IgnoreInTests for columns during codegen
  codegen/.snapshots/TestGenerateTemplate-should_add_ignore_in_tests_to_columns
  codegen/golang_test.go
  codegen/templates/column.go.tpl
Labels: feat

#156 feat: Test that JSON columns don't receive string values
  plugins/source_testing.go
Labels: automerge, feat

#157 feat(codegen): Add WithTypeTransformer
  codegen/golang.go
  codegen/golang_test.go
  codegen/table.go
Labels: feat

#162 chore(codegen): Restructure `codegen` package
  codegen/column.go
  codegen/doc.go
  codegen/golang.go
  codegen/options.go
  codegen/table.go
  codegen/table_test.go
  codegen/template.go
  codegen/template_test.go
  codegen/transformers.go
  codegen/util.go
  go.mod
  go.sum
Labels: automerge, ignore-for-release

#163 feat: Ignore specific field types
  codegen/table.go
  codegen/table_test.go
Labels: automerge, feat

#167 feat!: Remove ExampleConfig from client,servers and protobuf
  CONTRIBUTING.md
  Makefile
  clients/destination.go
  clients/source.go
  internal/pb/base.pb.go
  internal/pb/base.proto
  internal/pb/destination.pb.go
  internal/pb/destination.proto
  internal/pb/destination_grpc.pb.go
  internal/pb/source.pb.go
  internal/pb/source.proto
  internal/pb/source_grpc.pb.go
  internal/servers/destinations.go
  internal/servers/source.go
  plugins/destination.go
  plugins/source.go
  plugins/source_test.go
  serve/source_test.go
Labels: feat, breaking

#164 feat(codegen): Add `WithResolverTransformer` option
  codegen/column.go
  codegen/options.go
  codegen/table.go
  codegen/table_test.go
  codegen/transformers.go
Labels: automerge, feat

#172 fix: Fix typo in ValueTypeFromString
  schema/column.go
Labels: automerge, fix

#174 fix!: Make destinations work over gRPC only
  clients/destination.go
  clients/source.go
  internal/pb/base.pb.go
  internal/pb/base.proto
  internal/servers/destinations.go
  serve/source_test.go
Labels: fix, breaking

#179 fix: Added more informative error when there is no config files
  specs/spec.go
  specs/spec_reader.go
  specs/spec_reader_test.go
  specs/spec_test.go
  specs/testdata/valid/aws.yml
  specs/testdata/valid/postgresql.yml
  specs/testdata/wrong_source/invalid.yml
Labels: fix

#171 fix: Added custom toCamel, toSnake implementation
  caser/caser.go
  caser/caser_test.go
  caser/initialisms.go
  codegen/options.go
  codegen/table_test.go
  codegen/transformers.go
  go.mod
  go.sum
  schema/table.go
Labels: fix

#181 fix: Spec unmarshalling now supports defaults and validation
  specs/destination.go
  specs/destination_test.go
  specs/source.go
  specs/source_test.go
  specs/spec.go
  specs/spec_reader_test.go
  specs/spec_test.go
  specs/testdata/aws.yml
  specs/testdata/postgresql.yml
  specs/testdata/wrong_source/invalid.yml
Labels: fix

#183 feat!: SpecReader to support multiple files, dirs and yaml
  specs/spec_reader.go
  specs/spec_reader_test.go
  specs/testdata/dir/aws.yml
  specs/testdata/dir/postgresql.yml
  specs/testdata/gcp.yml
Labels: feat, breaking

#185 fix: Add SetDefault and Validate to SpecReader
  specs/spec_reader.go
  specs/testdata/dir/aws.yml
  specs/testdata/gcp.yml
Labels: fix

#187 fix: Streaming to destination plugin wasn't implemented correctly
  clients/destination.go
  internal/pb/destination.pb.go
  internal/pb/destination.proto
  internal/servers/destinations.go
Labels: automerge, fix

#188 fix: Validate versions only for github registry
  specs/destination.go
  specs/source.go
Labels: fix

#192 chore: Remove GCI from lint
  .golangci.yml
Labels: ignore-for-release

#191 fix: Add initialisms for k8s
  caser/caser_test.go
  caser/initialisms.go
Labels: fix

#195 test: Add test for spec validation
  specs/destination_test.go
Labels: test

#200 feat!: Remove ParentPathResolver
  schema/resolvers.go
Labels: automerge, feat, breaking

#201 feat!: Make CQUUIDResolver private
  schema/meta.go
  schema/resolvers.go
Labels: automerge, feat, breaking

#203 feat!: Rename ParentResourceFieldResolver to ParentColumnResolver
  schema/resolvers.go
Labels: automerge, feat, breaking

#202 feat!: Remove ParentIDResolver
  schema/resolvers.go
Labels: automerge, feat, breaking

#196 fix!: Avoid using global variables in caser
  caser/caser.go
  caser/caser_test.go
  caser/initialisms.go
  codegen/options.go
  codegen/table_test.go
  codegen/transformers.go
  schema/table.go
Labels: fix, breaking

#204 chore(codeowners): Set empty code owners for CHANGELOG.md
  CODEOWNERS
Labels: automerge, ignore-for-release

#206 feat: Move NewSourceClientSpawn (and dest) to SDK
  clients/destination.go
  clients/destination_test.go
  clients/download.go
  clients/logging.go
  clients/random.go
  clients/source.go
  clients/source_test.go
Labels: feat

#208 feat: Make NewSourceClient (and dest) as one interface
  clients/destination.go
  clients/destination_test.go
  clients/download.go
  clients/source.go
  clients/source_test.go
  serve/destination.go
  serve/destination_test.go
  serve/serve.go
  serve/source.go
  serve/source_test.go
Labels: feat

#205 feat(schema): Add schema.TypeTimeInterval
  codegen/table_test.go
  codegen/transformers.go
  schema/column.go
  schema/column_test.go
Labels: automerge, feat
