Repository cloudquery/plugin-sdk, pull requests merged in 2022-10, with the labels that each got.

#211 feat: Add Close() to destination interface and new writemode
  internal/pb/base.pb.go
  internal/pb/destination.pb.go
  internal/pb/destination.proto
  internal/pb/destination_grpc.pb.go
  internal/pb/source.pb.go
  internal/pb/source_grpc.pb.go
  internal/servers/destinations.go
  plugins/destination.go
  serve/destination_test.go
  specs/destination.go
Labels: feat

#218 chore: Remove Kodiak automerge in favor of Renovate
  .github/.kodiak.toml
Labels: automerge, ignore-for-release

#219 chore: Exclude more files from CODEOWNERS
  CODEOWNERS
Labels: automerge, ignore-for-release

#221 fix: Remove unused docs template function
  plugins/source_docs.go
Labels: automerge, fix

#226 fix: Remove redundant error print
  plugins/source_docs.go
Labels: fix

#227 chore(docs): Fix typos, broken links in markdown
  .github/styles/Vocab/Base/accept.txt
  .github/workflows/lint_markdown.yml
  CONTRIBUTING.md
Labels: automerge, ignore-for-release

#223 fix: Use correct path for Windows zip
  clients/download.go
Labels: fix

#220 fix: Create doc directory if doesn't exist
  plugins/source_docs.go
Labels: automerge, fix

#228 fix: Download destinations to 'destination' directory
  clients/destination.go
Labels: automerge, fix

#230 fix: Set default download directory to `.cq`
  clients/destination.go
  clients/download.go
  clients/source.go
Labels: automerge, fix

#231 fix: Use correct binary path on Windows
  clients/destination.go
  clients/download.go
  clients/source.go
Labels: automerge, fix

#224 feat!: Add overwrite-delete-stale mode for destination plugins
  clients/destination.go
  clients/destination_test.go
  clients/source.go
  clients/source_test.go
  internal/pb/base.pb.go
  internal/pb/destination.pb.go
  internal/pb/destination.proto
  internal/pb/destination_grpc.pb.go
  internal/pb/source.pb.go
  internal/pb/source.proto
  internal/pb/source_grpc.pb.go
  internal/servers/destinations.go
  internal/servers/source.go
  plugins/.snapshots/TestGenerateSourcePluginDocs-relation_table.md
  plugins/.snapshots/TestGenerateSourcePluginDocs-test_table.md
  plugins/destination.go
  plugins/source.go
  plugins/source_test.go
  plugins/source_testing.go
  plugins/templates/table.go.tpl
  schema/filters.go
  schema/meta.go
  schema/resolvers_test.go
  schema/resource.go
  schema/table.go
  schema/table_test.go
  serve/destination.go
  serve/destination_test.go
  serve/source.go
  serve/source_test.go
  specs/destination.go
  specs/destination_test.go
Labels: feat, breaking

#238 fix: Add progressbar instead of writers for Downloads
  clients/destination.go
  clients/download.go
  clients/source.go
  go.mod
  go.sum
Labels: fix

#240 fix: Improve download message
  clients/download.go
Labels: automerge, fix

#242 fix: Race condition in log streaming
  clients/destination.go
  clients/source.go
Labels: fix

#243 fix: Logging level
  clients/logging.go
Labels: fix

#246 fix: Plugin connection using Unix Domain Socket fixed for windows
  clients/destination.go
  clients/download.go
  clients/random.go
  clients/source.go
Labels: automerge, fix

#248 fix: Make progressbar work on small screens
  clients/download.go
Labels: automerge

#250 fix: Progressbar should go into stdout
  clients/download.go
Labels: automerge, fix

#251 fix: Stop if PreResourceResolver fails
  schema/table.go
Labels: automerge, fix

#252 fix: Exit gracefully on context cancelled
  clients/destination_test.go
  clients/source.go
  clients/source_test.go
  internal/servers/destinations.go
  serve/destination.go
  serve/destination_test.go
  serve/source.go
  serve/source_test.go
Labels: automerge, fix

#237 fix: Error on incorrect table configuration
  plugins/source.go
  plugins/source_test.go
Labels: automerge, fix

#257 fix: Recover panic in table resolver and object resolver flows
  schema/table.go
  schema/table_test.go
Labels: automerge, fix

#258 fix: Bug where first resource wasn't insert into DB
  internal/servers/destinations.go
Labels: fix

#260 fix: Add missing defer
  clients/destination.go
Labels: automerge, fix

#266 chore(ci): Trigger renovate after SDK release
  .github/workflows/release-pr.yml
Labels: automerge, ignore-for-release

#263 fix: Add custom log reader implementation to fix hang on long log lines
  clients/destination.go
  clients/log_reader.go
  clients/log_reader_test.go
  clients/source.go
Labels: automerge, fix

#268 feat!: Support table_concurrency and resource_concurrency
  plugins/source.go
  plugins/source_test.go
  schema/table.go
  schema/table_test.go
  serve/source_test.go
  specs/source.go
  specs/source_test.go
  specs/testdata/dir/aws.yml
  specs/testdata/gcp.yml
Labels: automerge, feat, breaking

#269 fix: DeleteStale feature
  plugins/.snapshots/TestGenerateSourcePluginDocs-relation_table.md
  plugins/.snapshots/TestGenerateSourcePluginDocs-test_table.md
  plugins/destination.go
  plugins/source.go
  plugins/source_docs.go
  schema/meta.go
  schema/table.go
Labels: automerge, fix

#273 fix: Ignore Sentry errors in dev (make comparison case insensitive)
  serve/destination.go
Labels: automerge, fix

#275 fix: Ignore sentry in development, case-insensitive for source plugins
  serve/source.go
Labels: automerge, fix

#271 fix: Make concurrency change backwards-compatible
  specs/source.go
Labels: automerge, fix

#277 fix: Remove DisallowUnknownFields from Source plugin server
  internal/servers/source.go
Labels: fix

#279 fix: Call Release on resource semaphore
  schema/table.go
Labels: automerge, fix

#283 feat: Add links to tables in table README.md, and list of relations
  plugins/.snapshots/TestGenerateSourcePluginDocs-README.md
  plugins/.snapshots/TestGenerateSourcePluginDocs-test_table.md
  plugins/source_docs_test.go
  plugins/templates/all_tables.go.tpl
Labels: automerge, feat

#285 fix: Fix sentry check for development environment
  serve/source.go
Labels: fix

#287 feat(tests): More faker options
  faker/faker.go
  faker/faker_test.go
  faker/options.go
Labels: automerge, feat

#288 chore: Add Issue to public roadmap project
  .github/workflows/issue_to_project.yml
Labels: automerge, ignore-for-release

#292 fix(tests): Parallel plugin testing, remove old faker
  go.mod
  go.sum
  plugins/source_testing.go
  schema/column_test.go
Labels: automerge, fix

#294 feat: Support application level protocol message.
  clients/destination.go
  clients/source.go
  internal/pb/base.pb.go
  internal/pb/base.proto
  internal/pb/destination.pb.go
  internal/pb/destination.proto
  internal/pb/destination_grpc.pb.go
  internal/pb/source.pb.go
  internal/pb/source.proto
  internal/pb/source_grpc.pb.go
  internal/servers/destinations.go
  internal/servers/source.go
  internal/versions/versions.go
  serve/source_test.go
Labels: automerge, feat

#295 fix: Use 'source' in error message instead of 'destination'
  clients/source.go
Labels: automerge, fix

#300 fix: Remove descriptions from table docs
  plugins/.snapshots/TestGenerateSourcePluginDocs-README.md
  plugins/.snapshots/TestGenerateSourcePluginDocs-relation_table.md
  plugins/.snapshots/TestGenerateSourcePluginDocs-test_table.md
  plugins/templates/all_tables.go.tpl
  plugins/templates/table.go.tpl
Labels: automerge, fix

#302 feat: Validate source plugin table and column names
  plugins/source.go
  plugins/source_test.go
  schema/resolvers_test.go
  schema/table.go
  schema/table_test.go
Labels: automerge, feat

#305 fix: Set Sentry server name to empty to avoid sending it
  serve/destination.go
  serve/source.go
Labels: automerge, fix

#312 fix(deps): Update go-funk
  go.mod
  go.sum
Labels: automerge, fix

#314 fix: Revert "fix(deps): Update go-funk (#312)"
  go.mod
  go.sum
Labels: fix

#318 feat: Add Metrics and improve scheduler with DFS
  clients/destination.go
  clients/source.go
  helpers/sync.go
  internal/pb/destination.pb.go
  internal/pb/destination.proto
  internal/pb/destination_grpc.pb.go
  internal/pb/source.pb.go
  internal/pb/source.proto
  internal/pb/source_grpc.pb.go
  internal/servers/destinations.go
  internal/servers/source.go
  internal/versions/versions.go
  plugins/destination.go
  plugins/destination_metrics.go
  plugins/source.go
  plugins/source_metrics.go
  plugins/source_metrics_test.go
  plugins/source_scheduler_dfs.go
  plugins/source_test.go
  plugins/source_testing.go
  plugins/source_validate_test.go
  schema/meta.go
  schema/resource.go
  schema/table.go
  schema/table_test.go
  serve/destination.go
  serve/destination_test.go
  serve/source.go
  serve/source_test.go
  specs/source.go
  specs/source_schema.json
  specs/source_test.go
  specs/validate.go
Labels: feat
