Repository cloudquery/plugin-sdk, pull requests merged in 2022-12, with the labels that each got.

#459 fix: Don't log start-and-finish of relational tables
  plugins/source_scheduler_dfs.go
Labels: fix

#456 fix: TablesForSpec should only return top-level tables
  plugins/source.go
  plugins/source_test.go
Labels: automerge, fix

#445 feat: Add Support for net.IP in Faker
  faker/faker.go
  faker/faker_test.go
Labels: automerge, feat

#455 fix: Sync Metrics for Long running plugins
  plugins/source_metrics.go
Labels: automerge, fix

#447 fix(codegen)!: Column type for slices
  codegen/table_test.go
  codegen/transformers.go
Labels: automerge, fix, breaking

#467 fix: Concurrent read,write to a map
  plugins/source.go
  plugins/source_scheduler_dfs.go
Labels: automerge, fix

#469 fix: Skip relations when initializing metrics
  plugins/source_scheduler_dfs.go
Labels: automerge, fix

#473 fix: Initialise clients only once
  plugins/source.go
  plugins/source_metrics.go
  plugins/source_scheduler_dfs.go
  plugins/source_test.go
Labels: automerge, fix

#481 feat: Add handling for json.Number in faker
  faker/faker.go
  faker/faker_test.go
Labels: automerge, feat

#476 fix: Allow both 'yml' and 'yaml' extensions
  specs/spec_reader.go
  specs/spec_reader_test.go
  specs/testdata/dir_yaml/aws.yaml
  specs/testdata/dir_yaml/postgresql.yaml
Labels: automerge, fix

#485 fix(errors): Remove usage of `codes.Internal`
  internal/servers/source.go
Labels: automerge, fix

#489 fix: Don't panic on empty-string for timestamp
  schema/timestamptz.go
  schema/timestamptz_test.go
Labels: automerge, fix

#491 fix: Reduce default concurrency
  specs/source.go
Labels: automerge, fix

#493 fix: Fix deadlock off-by-one
  plugins/source_scheduler_dfs.go
  plugins/source_test.go
Labels: automerge, fix

#494 fix: Glob table filtering
  schema/table.go
  schema/table_test.go
Labels: automerge, fix

#497 fix: Validate json strings and handle empty strings
  schema/json.go
  schema/json_test.go
Labels: automerge, fix

#499 fix: Throw error on empty env variable
  specs/spec_reader.go
  specs/spec_reader_test.go
Labels: automerge

#500 fix: Use json.Valid
  schema/json.go
  schema/json_test.go
Labels: automerge, fix

#503 fix: Don't print value with error on invalid JSON
  schema/json.go
Labels: automerge, fix

#505 fix: Include table name in logs on panic
  plugins/source_scheduler_dfs.go
Labels: automerge, fix

#516 fix: Move source & destination plugin code to separate packages
  clients/destination.go
  clients/source.go
  internal/servers/destinations.go
  internal/servers/source.go
  plugins/destination/memdb_plugin.go
  plugins/destination/metrics.go
  plugins/destination/plugin.go
  plugins/destination/plugin_test.go
  plugins/destination/reverse_transformer.go
  plugins/destination/testing.go
  plugins/source/.snapshots/TestGeneratePluginDocs-JSON-__tables.json
  plugins/source/.snapshots/TestGeneratePluginDocs-Markdown-README.md
  plugins/source/.snapshots/TestGeneratePluginDocs-Markdown-relation_relation_table.md
  plugins/source/.snapshots/TestGeneratePluginDocs-Markdown-relation_table.md
  plugins/source/.snapshots/TestGeneratePluginDocs-Markdown-test_table.md
  plugins/source/.snapshots/TestGenerateSourcePluginDocs-JSON-__tables.json
  plugins/source/.snapshots/TestGenerateSourcePluginDocs-Markdown-README.md
  plugins/source/.snapshots/TestGenerateSourcePluginDocs-Markdown-relation_relation_table.md
  plugins/source/.snapshots/TestGenerateSourcePluginDocs-Markdown-relation_table.md
  plugins/source/.snapshots/TestGenerateSourcePluginDocs-Markdown-test_table.md
  plugins/source/benchmark_test.go
  plugins/source/docs.go
  plugins/source/docs_test.go
  plugins/source/metrics.go
  plugins/source/metrics_test.go
  plugins/source/plugin.go
  plugins/source/plugin_test.go
  plugins/source/scheduler_dfs.go
  plugins/source/templates/all_tables.md.go.tpl
  plugins/source/templates/all_tables_entry.md.go.tpl
  plugins/source/templates/table.md.go.tpl
  plugins/source/testing.go
  plugins/source/validate.go
  serve/destination.go
  serve/destination_test.go
  serve/source.go
  serve/source_test.go
Labels: automerge, fix

#513 fix: Add better logging/metric per table
  plugins/source/scheduler_dfs.go
Labels: automerge, fix

#514 fix: Use correct error codes
  internal/servers/destinations.go
  internal/servers/source.go
Labels: automerge, fix

#492 fix: Improve formatting of newlines in markdown files
  plugins/source/.snapshots/TestGeneratePluginDocs-Markdown-README.md
  plugins/source/.snapshots/TestGeneratePluginDocs-Markdown-relation_relation_table.md
  plugins/source/.snapshots/TestGeneratePluginDocs-Markdown-relation_table.md
  plugins/source/.snapshots/TestGeneratePluginDocs-Markdown-test_table.md
  plugins/source/docs.go
Labels: automerge, fix

#519 fix(destination): Rename `NewDestinationPlugin` to `NewPlugin`
  plugins/destination/plugin.go
  plugins/destination/plugin_test.go
  serve/destination_test.go
Labels: automerge, fix

#522 chore(ci): Upgrade golangci-lint to v1.50.1
  .github/workflows/lint_golang.yml
Labels: ignore-for-release

#521 feat: Add managed API for destination plugins
  internal/memdb/memdb.go
  internal/memdb/memdb_test.go
  internal/testdata/testdata.go
  plugins/destination/managed_writer.go
  plugins/destination/memdb_plugin.go
  plugins/destination/plugin.go
  plugins/destination/plugin_testing.go
  plugins/destination/unmanaged_writer.go
  plugins/source/plugin.go
  schema/cidr_array.go
  schema/inet_array.go
  schema/int8_array.go
  schema/json.go
  schema/macaddr_array.go
  schema/text_array.go
  schema/timestamptz.go
  schema/types.go
  schema/uuid_array.go
  serve/destination_test.go
  specs/destination.go
  specs/destination_test.go
Labels: automerge, feat

#526 fix: Typo manager->managed
  internal/memdb/memdb_test.go
  plugins/destination/plugin.go
Labels: automerge, fix

#496 feat: Add basic periodic metric INFO logger
  plugins/source/metrics.go
  plugins/source/scheduler_dfs.go
Labels: automerge, feat

#484 refactor: Use `status.Convert` instead of `FromError`
  clients/destination.go
  clients/source.go
Labels: automerge, refactor

#483 refactor: Reduce nesting in clients->source->sync
  clients/source.go
Labels: automerge, refactor

#460 fix(destinations): Stop writing resources when channel is closed
  clients/destination.go
  clients/destination_test.go
Labels: automerge, fix

#529 fix: Don't hide errors in destination server
  internal/servers/destinations.go
Labels: automerge, fix

#534 feat: Make TestData public
  internal/memdb/memdb_test.go
  plugins/destination/plugin_testing.go
  serve/destination_test.go
  testdata/testdata.go
Labels: automerge, feat

#537 fix(destinations): Set done even if no resources to flush
  plugins/destination/managed_writer.go
Labels: automerge, fix

#540 feat(destinations): Allow plugins to set default batch size
  plugins/destination/plugin.go
  specs/destination.go
  specs/destination_test.go
  specs/spec_reader.go
Labels: automerge, feat

#543 chore: Clean up CI
  .github/workflows/lint_golang.yml
  .github/workflows/lint_markdown.yml
  .github/workflows/release-pr.yml
Labels: ignore-for-release
