Repository cloudquery/plugin-sdk, pull requests merged in 2022-11, with the labels that each got.

#322 fix: Try formatting timestamptz in a few formats
  cqtypes/timestamptz.go
Labels: fix

#336 fix: Parsing timestamptz default string
  cqtypes/timestamptz.go
  cqtypes/timestamptz_test.go
Labels: automerge, fix

#339 fix: Check for missing parent tables
  plugins/source.go
  plugins/source_validate.go
  plugins/source_validate_test.go
Labels: automerge, fix

#353 fix: Include source path in dest to source map key
  specs/spec_reader.go
  specs/spec_reader_test.go
  specs/testdata/multiple_sources.yml
Labels: fix

#360 fix: Dont use reflection in reverse transformer
  plugins/destination_reverse_transformer.go
Labels: automerge, fix

#362 chore: Start SDK semantic versioning from v1
  clients/destination.go
  clients/destination_test.go
  clients/source.go
  clients/source_test.go
  codegen/column.go
  codegen/table_test.go
  codegen/template_test.go
  codegen/transformers.go
  go.mod
  internal/servers/destinations.go
  internal/servers/source.go
  plugins/destination.go
  plugins/destination_reverse_transformer.go
  plugins/destination_testing.go
  plugins/source.go
  plugins/source_docs.go
  plugins/source_docs_test.go
  plugins/source_metrics.go
  plugins/source_scheduler_dfs.go
  plugins/source_test.go
  plugins/source_testing.go
  plugins/source_validate_test.go
  serve/destination.go
  serve/destination_test.go
  serve/source.go
  serve/source_test.go
Labels: ignore-for-release

#364 fix: Module parameter in logs of source-plugins
  plugins/source.go
Labels: automerge, fix

#366 fix: Revert "chore: Start SDK semantic versioning from v1"
  clients/destination.go
  clients/destination_test.go
  clients/source.go
  clients/source_test.go
  codegen/column.go
  codegen/table_test.go
  codegen/template_test.go
  codegen/transformers.go
  go.mod
  internal/servers/destinations.go
  internal/servers/source.go
  plugins/destination.go
  plugins/destination_reverse_transformer.go
  plugins/destination_testing.go
  plugins/source.go
  plugins/source_docs.go
  plugins/source_docs_test.go
  plugins/source_metrics.go
  plugins/source_scheduler_dfs.go
  plugins/source_test.go
  plugins/source_testing.go
  plugins/source_validate_test.go
  serve/destination.go
  serve/destination_test.go
  serve/source.go
  serve/source_test.go
Labels: automerge, fix

#363 fix: Allow managed clients to disable sentry logging
  clients/destination.go
  clients/source.go
  serve/destination.go
  serve/destination_test.go
  serve/env.go
  serve/source.go
  serve/source_test.go
Labels: automerge, fix

#352 fix: Normalize Windows line breaks before parsing configuration files
  .github/workflows/unittest.yml
  clients/destination_test.go
  clients/source_test.go
  codegen/template_test.go
  plugins/source_docs_test.go
  specs/spec_reader.go
  specs/spec_reader_test.go
Labels: automerge, fix

#368 fix: Make path a required config parameter
  plugins/source_test.go
  serve/source_test.go
  specs/destination.go
  specs/destination_test.go
  specs/source.go
  specs/source_test.go
  specs/testdata/multiple_sources.yml
Labels: automerge, fix

#369 feat: Add Testing suite for destination plugins
  internal/servers/destinations.go
  internal/testdata/testdata.go
  plugins/destination.go
  plugins/destination_memdb_plugin.go
  plugins/destination_test.go
  plugins/destination_testing.go
  schema/cidr_array.go
  schema/inet_array.go
  schema/int8_array.go
  schema/macaddr_array.go
  schema/text_array.go
  schema/uuid_array.go
  serve/destination_test.go
Labels: automerge, feat

#377 fix: Context cancelled too early for delete stale mode
  clients/destination.go
  clients/source.go
  plugins/destination.go
Labels: fix

#373 fix(faker): Use `MarshalText` for faker timestamps
  faker/faker.go
  schema/timestamptz_test.go
Labels: automerge, fix

#381 fix: Revert "fix(faker): Use `MarshalText` for faker timestamps (#373)"
  faker/faker.go
  faker/faker_test.go
  schema/timestamptz_test.go
Labels: automerge, fix

#384 fix: Update `resolveResource` timeout to 10 minutes
  plugins/source_scheduler_dfs.go
Labels: automerge, fix

#376 feat(codegen): Add sanity check to `TableDefinition`
  codegen/table.go
  codegen/table_test.go
Labels: feat

#382 fix: Use MarshalText when serializing timestamps when applicable
  schema/timestamptz.go
  schema/timestamptz_test.go
Labels: automerge, fix

#379 feat(codegen): Add `WithPKColumns` option
  codegen/options.go
  codegen/table.go
  codegen/table_test.go
  go.mod
  go.sum
Labels: automerge, feat

#389 fix(deps): Revert dependencies updates
  go.mod
  go.sum
Labels: fix

#391 fix: Close zip archive when we're done with it
  clients/destination_test.go
  clients/download.go
  clients/source_test.go
Labels: automerge, fix

#388 fix: Add -race when running tests
  Makefile
  plugins/source.go
  schema/validators_test.go
  serve/destination.go
  serve/destination_test.go
  serve/source.go
  serve/source_test.go
Labels: automerge, fix

#387 chore(codegen): Add check for column name
  codegen/table.go
  codegen/table_test.go
Labels: automerge, ignore-for-release

#349 fix: Clear skip tables error on invalid or child table skippage
  plugins/source_validate.go
  plugins/source_validate_test.go
Labels: automerge, fix

#396 fix: Pre-aggregate metrics before sending
  internal/servers/source.go
  serve/source_test.go
Labels: automerge, fix

#395 fix: Exit early if all Write workers have stopped
  plugins/destination.go
Labels: automerge, fix

#398 feat: Add support for glob matching in config
  internal/glob/LICENSE
  internal/glob/README.md
  internal/glob/glob.go
  internal/glob/glob_test.go
  plugins/source.go
  plugins/source_scheduler_dfs.go
  plugins/source_validate.go
  plugins/source_validate_test.go
  schema/table.go
Labels: automerge, feat

#403 fix: Change globbing behavior to include descendants by default
  plugins/source_validate.go
  plugins/source_validate_test.go
  schema/table.go
Labels: automerge, fix

#404 fix: Allow searching relations by name
  plugins/source_scheduler_dfs.go
  plugins/source_validate.go
  schema/table.go
Labels: fix

#406 fix: Update libs
  go.mod
  go.sum
  serve/destination.go
  serve/source.go
Labels: fix

#408 test: Add more non-happy flow tests
  plugins/destination_memdb_plugin.go
  plugins/destination_test.go
  serve/source_test.go
Labels: test

#410 fix: Workaround Go Inet marshal bug
  schema/cidr.go
  schema/inet.go
  schema/inet_test.go
Labels: automerge, fix

#347 feat: Add option to plugin doc command to output tables as JSON
  plugins/.snapshots/TestGenerateSourcePluginDocs-JSON-__tables.json
  plugins/.snapshots/TestGenerateSourcePluginDocs-Markdown-README.md
  plugins/.snapshots/TestGenerateSourcePluginDocs-Markdown-relation_table.md
  plugins/.snapshots/TestGenerateSourcePluginDocs-Markdown-test_table.md
  plugins/source_docs.go
  plugins/source_docs_test.go
  plugins/templates/all_tables.md.go.tpl
  plugins/templates/table.md.go.tpl
  serve/source.go
Labels: automerge, feat

#417 fix: Fix Destination testing suite
  plugins/destination_test.go
  plugins/destination_testing.go
Labels: automerge, fix

#415 chore: Add source plugin benchmark
  plugins/benchmark_test.go
  plugins/source_test.go
Labels: automerge, ignore-for-release

#418 feat: Support ${file:./path} expansion in spec
  specs/spec_reader.go
  specs/spec_reader_test.go
  specs/testdata/creds.txt
  specs/testdata/creds1.txt
  specs/testdata/gcp.yml
Labels: automerge, feat

#419 fix: Increase GRPC message size limit to 50MiB
  clients/constants.go
  clients/destination.go
  clients/source.go
  serve/constants.go
  serve/destination.go
  serve/source.go
Labels: automerge, fix

#416 feat: Resolve table relations in parallel
  plugins/source.go
  plugins/source_scheduler_dfs.go
Labels: automerge, feat

#422 fix: Revert "feat: Resolve table relations in parallel"
  plugins/source.go
  plugins/source_scheduler_dfs.go
Labels: automerge, fix

#423 feat: Resolve table relations in parallel
  plugins/source.go
  plugins/source_scheduler_dfs.go
Labels: automerge, feat

#432 fix: Small improvement to PK checking in codegen
  codegen/table.go
  codegen/table_test.go
Labels: fix

#425 chore: Run benchmarks in CI
  .github/workflows/unittest.yml
  .gitignore
  Makefile
  scripts/benchmark-delta/main.go
Labels: automerge, ignore-for-release

#436 chore: Use GH_CQ_BOT token to comment on Benchmark results
  .github/workflows/unittest.yml
Labels: ignore-for-release

#437 chore: Remove benchmark comments for now
  .github/workflows/unittest.yml
Labels: ignore-for-release

#431 fix(test): Values check test should account for `IgnoreInTests` column option
  plugins/source_test.go
  plugins/source_testing.go
Labels: automerge, fix

#430 feat: Handle resolving of empty maps and slices
  schema/json.go
  schema/json_test.go
Labels: automerge, feat

#441 chore(ci): Bring back benchmark comment
  .github/workflows/unittest-post.yml
  .github/workflows/unittest.yml
Labels: automerge, ignore-for-release

#442 chore(ci): Upload benchmark results only for ubuntu
  .github/workflows/unittest.yml
Labels: automerge, ignore-for-release

#440 feat: Add function to list tables that match a source spec
  clients/errors.go
  clients/source.go
  internal/pb/base.pb.go
  internal/pb/destination.pb.go
  internal/pb/destination_grpc.pb.go
  internal/pb/source.pb.go
  internal/pb/source.proto
  internal/pb/source_grpc.pb.go
  internal/servers/source.go
  plugins/source.go
  plugins/source_test.go
  serve/source_test.go
Labels: automerge, feat
