Repository cloudquery/plugin-sdk, pull requests merged in 2022-08, with the labels that each got.

#8 chore(main): Release 0.0.3
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending

#4 feat: CloudQuery v2
  .gitignore
  Makefile
  clients/destination.go
  clients/source.go
  clients/template.go
  codegen/doc.go
  codegen/golang.go
  codegen/golang_test.go
  codegen/table.go
  codegen/templates/column.go.tpl
  codegen/templates/table.go.tpl
  go.mod
  go.sum
  helpers/limit/limits.go
  helpers/limit/limits_test.go
  helpers/limit/sysctl_darwin.go
  helpers/limit/sysctl_freebsd.go
  helpers/limit/sysctl_linux.go
  helpers/limit/sysctl_windows.go
  helpers/limit/ulimit_freebsd.go
  helpers/limit/ulimit_unix.go
  helpers/limit/ulimit_win.go
  helpers/sync.go
  internal/pb/base.pb.go
  internal/pb/destination.pb.go
  internal/pb/destination.proto
  internal/pb/destination_grpc.pb.go
  internal/pb/source.pb.go
  internal/pb/source.proto
  internal/pb/source_grpc.pb.go
  internal/servers/destinations.go
  internal/servers/source.go
  plugins/destination.go
  plugins/source.go
  plugins/source_test.go
  plugins/source_test.go.backup
  plugins/source_testing.go
  plugins/verifiers.go
  schema/column.go
  schema/column_test.go
  schema/meta.go
  schema/resolvers.go
  schema/resource.go
  schema/table.go
  schema/validators_test.go
  serve/doc.go
  serve/serve.go
  serve/serve_test.go
  specs/connection.go
  specs/destination.go
  specs/registry.go
  specs/registry_test.go
  specs/source.go
  specs/source_schema.json
  specs/spec.go
  specs/spec_reader.go
  specs/spec_reader_test.go
  specs/spec_test.go
  specs/testdata/aws.cq.yml
  specs/testdata/pg.cq.yml
Labels: feat

#23 chore: Add Codecov
  .github/workflows/unittest.yml
Labels: ignore-for-release

#22 test: Add more unit tests
  plugins/destination.go
  plugins/source.go
  plugins/source_testing.go
  schema/resolvers.go
  schema/resolvers_test.go
  schema/resoruce_test.go
  schema/resource.go
  schema/resources_test.go.backup
  schema/table.go
  schema/table_test.go
  specs/destination_test.go
  specs/source_test.go
  specs/spec.go
Labels: test

#26 feat: Remove pgx dependency
  go.mod
  go.sum
  plugins/source_testing.go
Labels: feat

#30 feat: Improve gRPC status codes and remove .cq file suffix
  internal/pb/base.pb.go
  internal/pb/destination.pb.go
  internal/pb/destination.proto
  internal/pb/destination_grpc.pb.go
  internal/pb/source.pb.go
  internal/pb/source_grpc.pb.go
  internal/servers/source.go
  schema/table.go
  serve/serve_test.go
  specs/spec_reader.go
Labels: feat
