Repository cloudquery/plugin-sdk, pull requests merged in 2023-05, with the labels that each got.

#845 chore(test): Table for write append should also be modeled with timestamp
  plugins/destination/plugin_testing_write_append.go
Labels: automerge, ignore-for-release

#833 fix(arrow): Add missing table options
  schema/arrow.go
Labels: automerge, fix

#847 fix(arrow): Allow empty and `nil` valid param in `AppendValues`
  types/inet.go
  types/inet_test.go
  types/json.go
  types/json_test.go
  types/mac.go
  types/mac_test.go
  types/uuid.go
  types/uuid_test.go
Labels: automerge, fix

#849 chore(tests): Ensure interface contract between `types.XArray.ValueStr` & `types.XBuilder.AppendValueFromString`
  types/extensions_test.go
  types/inet.go
  types/json.go
  types/json_test.go
  types/mac.go
  types/uuid.go
Labels: automerge, ignore-for-release

#851 chore(UUID): Streamline UUID implementation
  types/uuid.go
Labels: automerge, ignore-for-release

#852 feat(deps): Upgrade to Apache Arrow v13 (latest `cqmain`)
  go.mod
  go.sum
  internal/memdb/memdb.go
  internal/memdb/memdb_test.go
  internal/pk/pk.go
  internal/servers/destination/v0/destinations.go
  plugins/destination/managed_writer.go
  plugins/destination/plugin.go
  plugins/destination/plugin_testing.go
  plugins/destination/plugin_testing_migrate.go
  plugins/destination/plugin_testing_overwrite.go
  plugins/destination/plugin_testing_overwrite_delete_stale.go
  plugins/destination/plugin_testing_write_append.go
  plugins/destination/unmanaged_writer.go
  schema/arrow.go
  schema/arrow_test.go
  schema/column.go
  schema/meta.go
  schema/schemas.go
  schema/table.go
  serve/destination_v0_test.go
  testdata/testdata.go
  types/extensions.go
  types/extensions_test.go
  types/inet.go
  types/inet_test.go
  types/json.go
  types/json_test.go
  types/mac.go
  types/mac_test.go
  types/uuid.go
  types/uuid_test.go
Labels: automerge, feat

#857 fix(writers): Assert unimplemented interface at compile-time
  plugins/destination/plugin.go
Labels: automerge, fix

#859 fix(testing): Wrong types in v3 testdata
  schema/testdata.go
Labels: automerge, fix

#868 feat(types): Rename Mac -> MAC
  internal/servers/destination/v0/schemav2tov3.go
  schema/testdata.go
  types/extensions.go
  types/extensions_test.go
  types/mac.go
  types/mac_test.go
Labels: automerge, feat

#869 feat(schema): Embed column creation options
  internal/servers/destination/v0/destinations.go
  internal/servers/destination/v0/schemav2tov3.go
  plugins/destination/plugin.go
  plugins/destination/plugin_testing_migrate.go
  schema/column.go
  schema/meta.go
  schema/table.go
  schema/testdata.go
  transformers/struct.go
  transformers/struct_test.go
Labels: automerge, feat

#863 feat: Allow testing of more Arrow types
  plugins/destination/plugin_testing.go
  plugins/destination/plugin_testing_migrate.go
  plugins/destination/plugin_testing_overwrite.go
  plugins/destination/plugin_testing_overwrite_delete_stale.go
  plugins/destination/plugin_testing_write_append.go
  schema/testdata.go
Labels: automerge, feat

#872 fix: Fix test column generation
  schema/testdata.go
  schema/testdata_test.go
Labels: automerge, fix

#876 fix(test): Remove extra `v2/schema` import
  schema/meta.go
  schema/testdata.go
Labels: automerge, fix

#878 feat(test): Test writing to a child table
  internal/memdb/memdb.go
  plugins/destination/plugin_testing_overwrite.go
  plugins/destination/plugin_testing_overwrite_delete_stale.go
  plugins/destination/plugin_testing_write_append.go
Labels: automerge, feat

#880 feat: Revert "feat(test): Test writing to a child table"
  internal/memdb/memdb.go
  plugins/destination/plugin_testing_overwrite.go
  plugins/destination/plugin_testing_overwrite_delete_stale.go
  plugins/destination/plugin_testing_write_append.go
Labels: automerge, feat

#882 fix: Flatten V2 tables
  internal/servers/destination/v0/destinations.go
  schema/table.go
  schema/table_test.go
Labels: automerge, fix

#884 fix(tables): Flatten stripping relations
  schema/table.go
  schema/table_test.go
Labels: automerge, fix

#887 fix(testing): CQ Parent ID column should not be NotNull
  schema/testdata.go
Labels: automerge, fix

#886 fix(destination): Don't duplicate tables to be removed
  plugins/destination/plugin.go
  plugins/destination/plugin_testing_overwrite_delete_stale.go
  schema/table.go
Labels: automerge, fix

#889 fix: Add null-row case for append-only tests
  plugins/destination/plugin_testing_write_append.go
  schema/testdata.go
Labels: automerge, fix

#892 feat: Refactor test options and allow skipping of nulls in lists
  internal/memdb/memdb_test.go
  plugins/destination/plugin_testing.go
  plugins/destination/plugin_testing_migrate.go
  plugins/destination/plugin_testing_overwrite.go
  plugins/destination/plugin_testing_overwrite_delete_stale.go
  plugins/destination/plugin_testing_write_append.go
  plugins/destination/strip_nulls.go
  schema/testdata.go
  schema/testdata_test.go
  serve/destination_v1_test.go
Labels: automerge, feat

#893 feat: Add precision options for dest testing
  plugins/destination/plugin_testing.go
  plugins/destination/plugin_testing_migrate.go
  plugins/destination/plugin_testing_overwrite.go
  plugins/destination/plugin_testing_overwrite_delete_stale.go
  plugins/destination/plugin_testing_write_append.go
  schema/testdata.go
Labels: automerge, feat

#894 fix: Inet extension MarshalJSON
  types/inet.go
Labels: automerge, fix

#898 fix(testdata): Don't use escaping in JSON testdata (as array.Approx will check the underlying data)
  schema/testdata.go
Labels: automerge, fix

#896 fix: Better handling for Arrow type strings in docs
  plugins/source/docs.go
  plugins/source/docs_test.go
  plugins/source/templates/table.md.go.tpl
  plugins/source/testdata/TestGeneratePluginDocs-JSON-__tables.json
  plugins/source/testdata/TestGeneratePluginDocs-Markdown-test_table.md
  types/inet.go
  types/json.go
Labels: automerge, fix

#906 fix: Transform `[]any` as `JSON`
  transformers/struct.go
  transformers/struct_test.go
Labels: automerge, fix

#905 fix: Test Decimal type, map type and larger number ranges
  go.mod
  plugins/destination/plugin_testing.go
  schema/testdata.go
Labels: automerge, fix

#913 feat(test): Add `AllowNull` option for test data
  plugins/destination/nulls.go
  plugins/destination/plugin_testing.go
  plugins/destination/plugin_testing_migrate.go
  plugins/destination/plugin_testing_overwrite.go
  plugins/destination/plugin_testing_overwrite_delete_stale.go
  plugins/destination/plugin_testing_write_append.go
  plugins/destination/strip_nulls.go
  types/inet.go
  types/mac.go
Labels: automerge, feat

#738 feat: Add the names of tables to the periodic logger
  plugins/source/metrics.go
  plugins/source/metrics_test.go
  plugins/source/scheduler.go
  plugins/source/scheduler_dfs.go
Labels: automerge, feat
