Repository cloudquery/plugin-sdk, pull requests merged in 2023-12, with the labels that each got.

#1401 fix: Fail early on usage client init if token is not set
  premium/usage.go
  premium/usage_test.go
Labels: automerge, fix

#1403 feat: Add `GetPaidTables()` and `HasPaidTables()` to `schema.Tables`
  schema/table.go
Labels: feat

#1405 feat: Include `is_paid` field when creating tables json during package
  examples/simple_plugin/go.mod
  examples/simple_plugin/go.sum
  go.mod
  go.sum
  internal/memdb/memdb.go
  serve/package.go
  serve/testdata/memdbtables.json
Labels: automerge, feat

#1411 feat: Individual Table and Client rate limit
  scheduler/scheduler.go
  scheduler/scheduler_dfs.go
Labels: automerge, feat

#1415 fix: Update usage limit message
  premium/monitor.go
  premium/monitor_test.go
  premium/tables.go
  premium/usage.go
Labels: automerge, fix

#1418 fix(tests): Find empty columns for JSON types
  schema/validators.go
  schema/validators_test.go
Labels: automerge, fix

#1429 feat: Faker should preserve previous values, if set
  faker/faker.go
  faker/faker_test.go
Labels: feat

#1430 feat: Expose otel headers and url_path as flags
  serve/plugin.go
Labels: automerge, feat

#1436 feat: Offline licensing support
  examples/simple_plugin/go.mod
  examples/simple_plugin/go.sum
  plugin/meta.go
  plugin/plugin.go
  premium/offline.go
  premium/offline.key
  premium/offline_test.go
  premium/usage.go
  premium/usage_test.go
  serve/plugin.go
Labels: feat

#1439 chore: Fix tests/races
  premium/usage_test.go
  scheduler/scheduler_test.go
Labels: automerge, ignore-for-release
