Repository cloudquery/plugin-sdk, pull requests merged in 2023-10, with the labels that each got.

#1267 fix: Add `linux_arm64` to default build targets
  plugin/plugin_package.go
Labels: automerge, fix

#1270 fix: Serialize columns during package
  .github/workflows/unittest.yml
  examples/simple_plugin/go.mod
  examples/simple_plugin/go.sum
  go.mod
  go.sum
  internal/memdb/memdb.go
  serve/package.go
  serve/package_test.go
  serve/testdata/memdbtables.json
Labels: automerge, fix

#1276 chore: Test scheduler strategy JSON schema
  scheduler/strategy.go
  scheduler/strategy.json
  scheduler/strategy_test.go
Labels: automerge, ignore-for-release

#1280 fix: Only warn on validation err
  plugin/plugin.go
Labels: automerge, fix

#1282 feat: Support Delete Record
  internal/memdb/memdb.go
  internal/servers/plugin/v3/plugin.go
  message/sync_message.go
  message/write_message.go
  plugin/testing_write.go
  plugin/testing_write_delete.go
  writers/mixedbatchwriter/mixedbatchwriter.go
  writers/mixedbatchwriter/mixedbatchwriter_test.go
  writers/mixedbatchwriter/unimplemented.go
  writers/mixedbatchwriter/unimplemented_test.go
  writers/msgtype.go
Labels: automerge, feat

#1292 feat: Add support for conditional static linking of C lib to builds
  plugin/options.go
  plugin/plugin.go
  serve/package.go
Labels: feat

#1295 feat: Support DeleteRecord in all writers
  writers/batchwriter/batchwriter.go
  writers/batchwriter/batchwriter_test.go
  writers/batchwriter/unimplemented.go
  writers/batchwriter/unimplemented_test.go
  writers/streamingbatchwriter/streamingbatchwriter.go
  writers/streamingbatchwriter/streamingbatchwriter_test.go
  writers/streamingbatchwriter/unimplemented.go
  writers/streamingbatchwriter/unimplemented_test.go
Labels: automerge, feat

#1299 fix: Enable Skipping of DeleteRecord tests
  plugin/testing_write.go
Labels: automerge, fix

#1303 feat: Add JSON schema for `configtype.Duration`
  configtype/duration.go
  configtype/duration_test.go
  scheduler/strategy_test.go
Labels: automerge, feat

#1310 fix: Make static linking conditional only for Linux
  serve/package.go
Labels: automerge, fix

#1316 fix: Set all fields in `DeleteRecord` message
  internal/servers/plugin/v3/plugin.go
Labels: automerge, fix

#1313 feat: Support publishing plugins with team and kind metadata set
  examples/simple_plugin/client/client.go
  examples/simple_plugin/plugin/plugin.go
  plugin/options.go
  plugin/plugin.go
  serve/info.go
  serve/package.go
  serve/package_test.go
  serve/plugin.go
Labels: automerge, feat

#1321 fix(package): Only return one level down of relations when writing `tables.json`
  internal/memdb/memdb.go
  serve/package.go
  serve/plugin_test.go
  serve/testdata/memdbtables.json
Labels: automerge, fix

#1325 feat: Add OnBeforeSend hook
  internal/servers/plugin/v3/plugin.go
  plugin/plugin.go
Labels: automerge, feat

#1327 feat: Add IsPaid flag to table definition
  schema/arrow.go
  schema/table.go
Labels: automerge, feat

#1326 feat: Adding a batch updater to allow usage updates to be batched
  go.mod
  go.sum
  premium/usage.go
  premium/usage_test.go
Labels: automerge, feat

#1334 feat: Allow sync to be cancelled when in progress
  internal/servers/plugin/v3/plugin.go
  plugin/plugin.go
  scheduler/scheduler.go
  scheduler/scheduler_dfs.go
  scheduler/scheduler_test.go
Labels: automerge, feat

#1333 feat: Adding quota monitoring for premium plugins
  go.mod
  go.sum
  premium/monitor.go
  premium/monitor_test.go
  premium/tables.go
  premium/tables_test.go
  premium/usage.go
  premium/usage_test.go
  scheduler/scheduler.go
Labels: automerge, feat

#1339 fix: Fix nil pointer dereference when remaining rows not set
  premium/usage.go
Labels: automerge, fix
