Repository cloudquery/plugin-sdk, pull requests merged in 2023-08, with the labels that each got.

#1123 fix: Check record equality before generating diff
  plugin/diff.go
Labels: automerge, fix

#1127 fix: Nulls in lists
  plugin/nulls.go
  plugin/nulls_test.go
Labels: automerge, fix

#1131 fix(writers): StreamingBatchWriter hangs with non-append mode
  writers/streamingbatchwriter/mocktimer_test.go
  writers/streamingbatchwriter/streamingbatchwriter.go
  writers/streamingbatchwriter/streamingbatchwriter_test.go
  writers/streamingbatchwriter/unimplemented.go
Labels: automerge, fix

#1129 feat: Add more metadata to tables needed for docs generation
  schema/arrow.go
  schema/table.go
  schema/table_test.go
Labels: automerge, feat

#1136 fix(plugin-tables): Add missing `skip_dependent_tables`
  go.mod
  go.sum
  internal/servers/plugin/v3/plugin.go
Labels: automerge

#1138 feat: Add Unflatten tables method
  schema/table.go
  schema/table_test.go
Labels: automerge, feat

#1109 fix: Scalar timestamp parsing
  scalar/timestamp.go
  scalar/timestamp_test.go
Labels: automerge, fix

#1108 fix: Bring back plugin validation
  plugin/plugin.go
  plugin/validate.go
  schema/table.go
  schema/table_test.go
Labels: automerge, fix

#1152 chore(ci): Mark SDK updates to the example plugin as `chore`
  .github/renovate.json5
Labels: automerge, ignore-for-release

#1153 fix: Change `testdata.Generate` signature
  plugin/diff.go
  plugin/nulls_test.go
  plugin/testing_upsert.go
  plugin/testing_write_delete.go
  plugin/testing_write_insert.go
  plugin/testing_write_migrate.go
  schema/testdata.go
Labels: automerge, fix

#1157 fix: Ease diff code reading
  plugin/diff.go
  schema/testdata.go
Labels: automerge, fix

#1160 fix: Fix testdata generation
  internal/memdb/memdb.go
  plugin/sort.go
  plugin/testing_upsert.go
  plugin/testing_write_insert.go
  plugin/testing_write_migrate.go
  schema/testdata.go
Labels: automerge, fix

#1163 fix: Skip double migration test in forced mode
  plugin/testing_write_migrate.go
Labels: automerge, fix

#1166 chore: Update CODEOWNERS
  CODEOWNERS
Labels: ignore-for-release

#932 test(scalar): Add google/uuid test
  scalar/uuid_test.go
Labels: automerge, test

#1167 fix: Don't send migrate messages in destination v1 write
  internal/servers/destination/v1/destinations.go
Labels: automerge, fix
