Repository cloudquery/plugin-sdk, pull requests merged in 2023-02, with the labels that each got.

#651 fix: Handle numbers in env variables
  specs/spec_reader.go
  specs/spec_reader_test.go
  specs/testdata/number.txt
  specs/testdata/numbers.yml
Labels: automerge, fix

#659 fix(logging): Log more explicit message when OOM and other status codes occur
  clients/destination/v0/destination_terminate.go
  clients/source/v1/source_terminate.go
Labels: automerge, fix

#658 fix: Trap terminate signal, log which signal we received
  serve/destination.go
  serve/source.go
Labels: automerge, fix

#661 fix: Remove unused `OnlyIncrementalTables` spec property
  specs/source.go
Labels: automerge, fix

#662 feat: Add skip_dependent_tables option
  plugins/destination/plugin.go
  plugins/source/plugin.go
  schema/table.go
  schema/table_test.go
  specs/source.go
Labels: automerge, feat

#654 feat: Enable Custom Validators
  plugins/source/testing.go
Labels: automerge, feat

#532 test: Add null-in-text-field test
  schema/text.go
  schema/types.go
  testdata/testdata.go
Labels: automerge, test

#664 feat: Use Setpgid=true on Unix systems so that signals are not sent to the child process
  clients/destination/v0/destination.go
  clients/destination/v0/destination_unix.go
  clients/destination/v0/destination_windows.go
  clients/source/v1/source.go
  clients/source/v1/source_unix.go
  clients/source/v1/source_windows.go
Labels: automerge, feat

#668 feat: Add table diff methods
  cloudquery/destination/v0/destination.proto
  internal/memdb/memdb.go
  internal/pb/destination/v0/destination.pb.go
  internal/servers/destination/v0/destinations.go
  plugins/destination/plugin.go
  plugins/destination/plugin_testing.go
  plugins/source/plugin.go
  schema/column.go
  schema/table.go
  schema/table_test.go
Labels: automerge, feat

#670 fix: Remove duplicate force implementation
  cloudquery/destination/v0/destination.proto
  internal/memdb/memdb.go
  internal/pb/destination/v0/destination.pb.go
  internal/servers/destination/v0/destinations.go
  plugins/destination/plugin.go
  plugins/destination/plugin_testing.go
Labels: automerge, fix

#671 fix: Destination testing add force tests
  plugins/destination/plugin_testing.go
  plugins/destination/plugin_testing_migrate.go
  plugins/destination/plugin_testing_overwrite.go
  plugins/destination/plugin_testing_overwrite_delete_stale.go
  plugins/destination/plugin_testing_write_append.go
  schema/column.go
  schema/table.go
  schema/table_test.go
Labels: automerge, fix

#678 fix: Potential database lock/race in destination testing
  plugins/destination/plugin_testing.go
  plugins/destination/plugin_testing_migrate.go
  plugins/destination/plugin_testing_overwrite.go
  plugins/destination/plugin_testing_overwrite_delete_stale.go
  plugins/destination/plugin_testing_write_append.go
Labels: automerge, fix

#680 fix: Take2 of fixing race in destination testing
  internal/memdb/memdb_test.go
  plugins/destination/plugin_testing.go
Labels: automerge, fix

#681 chore(ci-lint): Remove verbose flag
  .github/workflows/lint_golang.yml
Labels: automerge, ignore-for-release

#683 fix: Fix race in dest testing try 3
  plugins/destination/plugin_testing.go
Labels: automerge, fix

#685 fix: Make sure _cq_id unique across all dest plugins
  plugins/destination/plugin.go
  schema/meta.go
  schema/type_test.go
Labels: automerge, fix

#686 fix: Set _cq_id not null for all tables
  plugins/destination/plugin.go
Labels: automerge, fix

#688 feat: Improve migration detection APIs
  internal/memdb/memdb.go
  internal/memdb/memdb_test.go
  plugins/destination/plugin_testing.go
  plugins/destination/plugin_testing_migrate.go
  schema/column.go
  schema/table.go
  schema/table_test.go
Labels: automerge, feat

#690 fix: Better string methods for TableColumnChange
  schema/table.go
Labels: automerge, fix

#691 chore: Add links to readme
  README.md
Labels: ignore-for-release

#696 fix(test-migrate): Ignore order when comparing resources read
  plugins/destination/plugin_testing_migrate.go
Labels: automerge, fix

#695 fix(test-migrate): Add CqId to migrate tests tables
  plugins/destination/plugin_testing_migrate.go
Labels: automerge, fix

#702 feat(schema): Add Unique column option, set it for CqID
  schema/column.go
  schema/meta.go
Labels: automerge, feat

#704 fix(destination): Set CqID to unique at the destination level
  plugins/destination/plugin.go
Labels: automerge, fix

#624 feat(spec): Return sources, destinations in order
  specs/spec_reader.go
  specs/spec_reader_test.go
Labels: automerge, feat

#710 fix: Cleanup code
  schema/array.go
  schema/inet_test.go
  schema/resource.go
Labels: fix

#715 chore: Remove issues triage workflow
  .github/workflows/issue_to_project.yml
Labels: automerge, ignore-for-release
