Repository cloudquery/plugin-sdk, pull requests merged in 2023-07, with the labels that each got.

#1039 fix: State add flush and fix migration bug
  .github/workflows/unittest-post.yml.backup
  internal/clients/state/v3/state.go
  state/state.go
Labels: automerge, fix

#1031 fix(serve): Confusing message
  serve/plugin.go
Labels: automerge, fix

#1041 fix: Add GetMessageByTable to WriteMigrateTables
  message/write_message.go
Labels: automerge, fix

#1038 feat(writers): More unimplemented writer helpers
  writers/batchwriter/unimplemented.go
  writers/batchwriter/unimplemented_test.go
  writers/mixedbatchwriter/unimplemented.go
  writers/mixedbatchwriter/unimplemented_test.go
  writers/streamingbatchwriter/unimplemented.go
  writers/streamingbatchwriter/unimplemented_test.go
Labels: automerge, feat

#1046 fix: Make scheduler stateful to support sync option
  go.mod
  go.sum
  internal/servers/plugin/v3/plugin.go
  plugin/plugin_source.go
  scheduler/scheduler.go
  scheduler/scheduler_dfs.go
  scheduler/scheduler_round_robin.go
  scheduler/scheduler_test.go
Labels: automerge, fix

#1045 fix(writers): Require `Close()` for `StreamingBatchWriter`
  writers/streamingbatchwriter/streamingbatchwriter.go
Labels: automerge, fix

#1047 feat: Add state.NoOpClient
  state/state.go
Labels: automerge, feat

#1053 feat: Add `WriteInserts.GetRecords()`
  message/write_message.go
Labels: automerge, feat

#1056 fix: Fix timer logic in batch writers
  writers/batchwriter/batchwriter.go
  writers/streamingbatchwriter/streamingbatchwriter.go
Labels: automerge, fix

#1059 fix(configtype): Add `Equal()` method to `Duration`
  configtype/duration.go
  configtype/duration_test.go
Labels: automerge, fix

#1061 fix(testdata): Add missing column types
  schema/testdata.go
Labels: automerge, fix

#1062 fix: Check record data in tests
  plugin/testing_upsert.go
  plugin/testing_write_delete.go
  plugin/testing_write_insert.go
  plugin/testing_write_migrate.go
Labels: automerge, fix

#1064 fix: Conversion and test fixes
  scalar/scalar.go
  scalar/struct.go
  scalar/struct_test.go
  schema/testdata.go
Labels: fix

#1058 refactor(ticker): Don't reset manually
  writers/batchwriter/batchwriter.go
  writers/mixedbatchwriter/mixedbatchwriter.go
  writers/mixedbatchwriter/mixedbatchwriter_test.go
  writers/streamingbatchwriter/mocktimer_test.go
  writers/streamingbatchwriter/streamingbatchwriter.go
  writers/streamingbatchwriter/streamingbatchwriter_test.go
  writers/ticker.go
Labels: automerge, refactor

#1065 fix: Add AddCqIDs helper function
  schema/table.go
Labels: automerge, fix

#1066 fix: Fix test assertions for records
  plugin/testing_write_migrate.go
Labels: automerge, fix

#1070 fix(naming): Rename `SyncMessages.InsertMessage()` to `SyncMessages.GetInserts()`
  message/sync_message.go
Labels: automerge, fix

#1067 fix(testdata): Exclude only the correct type
  schema/testdata.go
Labels: automerge, fix

#1068 fix(scalar): Test `AppendTime` on TimestampBuilder
  scalar/timestamp_test.go
Labels: automerge, fix

#1072 fix: Deterministic ordering for records returned by readAll in tests
  internal/memdb/memdb.go
  plugin/plugin_read.go
  plugin/plugin_source.go
  plugin/sort.go
  plugin/testing_upsert.go
  plugin/testing_write_insert.go
  plugin/testing_write_migrate.go
  schema/testdata.go
  schema/testdata_test.go
Labels: automerge, fix

#1069 feat(transformers): Add `Apply` to apply extra transformations
  transformers/tables.go
Labels: automerge, feat

#1075 fix: Reverse order of records in memdb
  internal/memdb/memdb.go
  plugin/testing_write_insert.go
Labels: automerge, fix

#1074 fix: Handle null-related test options
  plugin/nulls.go
  plugin/testing_upsert.go
  plugin/testing_write_delete.go
  plugin/testing_write_insert.go
  plugin/testing_write_migrate.go
Labels: automerge, fix

#1076 fix: Reset timers on flush
  writers/batchwriter/batchwriter.go
  writers/mixedbatchwriter/mixedbatchwriter.go
  writers/mixedbatchwriter/mixedbatchwriter_test.go
  writers/streamingbatchwriter/mocktimer_test.go
  writers/streamingbatchwriter/streamingbatchwriter.go
  writers/streamingbatchwriter/streamingbatchwriter_test.go
  writers/ticker.go
Labels: automerge, fix

#1077 fix(scheduler): Concurrency as `int`
  scheduler/scheduler.go
Labels: automerge, fix

#1079 fix: Use background ctx in batchwriter worker
  writers/batchwriter/batchwriter.go
Labels: automerge, fix

#1087 chore(ci): Bring back unittest-post, scope runners names to SDK
  .github/workflows/lint_golang.yml
  .github/workflows/unittest-post.yml
  .github/workflows/unittest.yml
Labels: automerge, ignore-for-release

#1089 fix(testing): Comply with given TimePrecision
  plugin/testing_upsert.go
  plugin/testing_write_insert.go
Labels: automerge, fix

#1086 fix: Add random suffix to test table names
  plugin/testing.go
  plugin/testing_upsert.go
  plugin/testing_write.go
  plugin/testing_write_delete.go
  plugin/testing_write_insert.go
Labels: automerge, fix

#1085 feat: Add `plugin.ValidateNoEmptyColumns`
  message/sync_message.go
  plugin/testing_validation.go
Labels: automerge, feat

#1092 fix: Add `NoConnection` to init request
  go.mod
  go.sum
  internal/servers/plugin/v3/plugin.go
Labels: automerge, fix

#1082 fix: Differentiate between errgroup context and global context being cance…
  internal/servers/plugin/v3/plugin.go
Labels: automerge, fix

#1097 feat: Add initial version of open-telemetry
  go.mod
  go.sum
  scheduler/scheduler.go
  scheduler/scheduler_dfs.go
  serve/opentelemetry.go
  serve/plugin.go
Labels: automerge, feat

#1101 fix(testing): Force migrations should allow table drops
  plugin/testing_write_migrate.go
Labels: fix

#1103 fix(streamingbatchwriter): Missing tickerFn on DeleteWorker
  writers/streamingbatchwriter/streamingbatchwriter.go
Labels: automerge, fix
