Repository cloudquery/plugin-sdk, pull requests merged in 2023-09, with the labels that each got.

#1187 fix(test): Truncate sync time based on test options in `testDeleteStaleBasic`
  plugin/testing_write_delete.go
Labels: automerge, fix

#1189 fix: Basic delete stale test
  plugin/testing_write_delete.go
Labels: automerge, fix

#1191 chore: Update CODEOWNERS
  CODEOWNERS
Labels: automerge, ignore-for-release

#1195 fix: Use tables with primary key in `delete-stale` tests
  plugin/testing_write_delete.go
  plugin/testing_write_upsert.go
Labels: automerge, fix

#1148 fix(caser): ToSnake does not replace spaces with _
  caser/caser.go
  caser/caser_test.go
Labels: automerge, fix

#1107 refactor: Dedup tables only at the top level in `FlattenTables`
  schema/table.go
Labels: automerge, refactor

#1200 feat: Export `grpczerolog` for reuse
  helpers/grpczerolog/grpc.go
  helpers/slice.go
  serve/plugin.go
Labels: automerge, feat

#1211 feat: Update package command
  .github/workflows/lint_markdown.yml
  examples/simple_plugin/docs/configuration.md
  examples/simple_plugin/docs/overview.md
  plugin/options.go
  plugin/plugin.go
  plugin/plugin_package.go
  plugin/plugin_publish.go
  serve/package.go
  serve/package_test.go
  serve/plugin.go
  serve/publish.go
  serve/publish_test.go
Labels: automerge, feat

#1212 fix: Add schema version to package.json
  serve/package.go
  serve/package_test.go
Labels: automerge, fix

#1217 feat: Add Checksums to package.json format
  serve/package.go
  serve/package_test.go
  serve/testdata/message.txt
Labels: automerge, feat

#1218 feat: Add shuffle scheduler
  scheduler/scheduler.go
  scheduler/scheduler_shuffle.go
Labels: automerge, feat

#1214 feat: Add support for jsonschema
  examples/simple_plugin/go.mod
  examples/simple_plugin/go.sum
  go.mod
  go.sum
  plugin/options.go
  plugin/plugin.go
Labels: automerge, feat

#1223 fix: Validate spec only when connection is established
  plugin/plugin.go
Labels: automerge, fix, priority merge

#1227 fix(package): Normalize tables when writing tables.json
  internal/memdb/memdb.go
  serve/package.go
  serve/package_test.go
  serve/plugin_test.go
Labels: fix

#1229 test: Update tests
  serve/package_test.go
  serve/plugin_test.go
Labels: automerge, test

#1231 fix: Enable format assertion for JSON schema
  plugin/plugin.go
Labels: automerge, fix

#1233 feat: Expose `plugin.JSONSchemaValidator` to be used in schema tests
  plugin/plugin.go
  plugin/validate.go
Labels: automerge, feat

#1226 fix(scalar): Don't pass typed nils in list values
  scalar/list.go
  scalar/list_test.go
Labels: automerge, fix

#1238 fix: Skip tables.json when packaging destinations
  examples/simple_plugin/plugin/client.go
  plugin/plugin_package.go
  serve/package.go
  serve/package_test.go
Labels: automerge, fix

#1240 fix: Rename plugin type -> kind for consistency with existing configs
  plugin/plugin_package.go
  serve/package.go
  serve/package_test.go
Labels: automerge, fix

#1243 feat: Provide User with actionable error message when no tables are configured for syncing
  scheduler/scheduler.go
  scheduler/scheduler_test.go
Labels: automerge, feat

#1249 fix(package): Don't init destinations during package
  serve/package.go
Labels: automerge, fix

#1255 chore: Go 1.21 follow-ups
  .github/workflows/lint_golang.yml
  .golangci.yml
  internal/random/random.go
  message/sync_message.go
  message/write_message.go
  schema/resource.go
  schema/table.go
  state/state.go
  transformers/struct.go
  transformers/struct_test.go
Labels: automerge, ignore-for-release

#1254 feat: Add JSON schema to scheduler strategy
  examples/simple_plugin/go.mod
  examples/simple_plugin/go.sum
  go.mod
  go.sum
  scheduler/scheduler.go
  scheduler/strategy.go
  scheduler/strategy.json
  scheduler/strategy_test.go
Labels: automerge, feat
