Repository cloudquery/plugin-sdk, pull requests merged in 2023-06, with the labels that each got.

#921 fix(test): Use `array.WithUnorderedMapKeys`
  go.mod
  go.sum
  plugins/destination/diff.go
  plugins/destination/plugin_testing.go
  plugins/destination/plugin_testing_migrate.go
  plugins/destination/plugin_testing_overwrite.go
  plugins/destination/plugin_testing_overwrite_delete_stale.go
  plugins/destination/plugin_testing_write_append.go
Labels: automerge, fix

#930 fix(testdata): Match map field names with type
  schema/testdata.go
Labels: automerge, fix

#914 feat: More scalars
  helpers/integers.go
  plugins/source/plugin_test.go
  scalar/binary.go
  scalar/bool.go
  scalar/date32.go
  scalar/date32_test.go
  scalar/date64.go
  scalar/date64_test.go
  scalar/decimal.go
  scalar/duration.go
  scalar/duration_test.go
  scalar/float.go
  scalar/float_test.go
  scalar/inet.go
  scalar/int.go
  scalar/int_test.go
  scalar/interval.go
  scalar/json.go
  scalar/list.go
  scalar/list_test.go
  scalar/mac.go
  scalar/scalar.go
  scalar/scalar_test.go
  scalar/string.go
  scalar/struct.go
  scalar/struct_test.go
  scalar/time.go
  scalar/timestamp.go
  scalar/timestamp_test.go
  scalar/uint.go
  scalar/uint_test.go
  scalar/uuid.go
Labels: automerge, feat

#922 fix(scalar): Handle nil pointer to []byte in uuid and binary
  scalar/binary.go
  scalar/binary_test.go
  scalar/bool_test.go
  scalar/float_test.go
  scalar/uuid.go
  scalar/uuid_test.go
Labels: automerge, fix

#938 feat(scalar): Support pointer dereferencing in decimal
  scalar/decimal.go
  scalar/decimal_test.go
Labels: automerge, feat

#942 fix: Remove uint validation
  scalar/int.go
Labels: automerge, fix

#959 chore: Disable `depguard`
  .golangci.yml
Labels: automerge, ignore-for-release

#956 fix(transformers): Ability to transform `any` with TypeTransformer
  transformers/struct.go
  transformers/struct_test.go
Labels: automerge, fix

#964 fix: Don't write last batch in managed writer if the context was canceled
  plugins/destination/managed_writer.go
Labels: automerge, fix

#995 fix: Close files in docs
  docs/markdown.go
Labels: automerge, fix

#997 fix: Set Sync option fields
  internal/servers/plugin/v3/plugin.go
  plugin/plugin_source.go
  scheduler/scheduler.go
  scheduler/scheduler_dfs.go
  scheduler/scheduler_round_robin.go
  scheduler/scheduler_test.go
Labels: automerge, fix

#1003 fix(testing): Grammar
  plugin/testing_write_delete.go
  plugin/testing_write_insert.go
  plugin/testing_write_migrate.go
Labels: automerge, fix

#1009 feat: Split sync and write messages
  go.mod
  go.sum
  internal/clients/state/v3/state.go
  internal/memdb/memdb.go
  internal/memdb/memdb_test.go
  internal/servers/destination/v0/destinations.go
  internal/servers/destination/v1/destinations.go
  internal/servers/plugin/v3/plugin.go
  internal/servers/plugin/v3/plugin_test.go
  message/sync_message.go
  message/write_message.go
  plugin/plugin.go
  plugin/plugin_destination.go
  plugin/plugin_source.go
  plugin/plugin_test.go
  plugin/testing_upsert.go
  plugin/testing_write_delete.go
  plugin/testing_write_insert.go
  plugin/testing_write_migrate.go
  scheduler/scheduler.go
  scheduler/scheduler_test.go
  serve/destination_v0_test.go
  serve/destination_v1_test.go
  serve/plugin_test.go
  writers/batch.go
  writers/batch_test.go
  writers/mixed_batch.go
  writers/mixed_batch_test.go
Labels: automerge, feat

#1006 fix: Update scheduler for JSON marshal / unmarshal
  scheduler/scheduler.go
  scheduler/scheduler_test.go
  writers/batch.go
  writers/mixed_batch.go
Labels: automerge, fix

#1008 fix(batchwriter): Allow zero batch size, flush before exceeding batch size instead of after
  writers/batch.go
  writers/batch_test.go
Labels: automerge, fix

#1004 feat: Add StreamingBatchWriter
  writers/mixed_batch.go
  writers/msgtype.go
  writers/streamingbatch.go
  writers/streamingbatch_test.go
Labels: automerge, feat

#1015 fix: Add back testing for all types
  plugin/testing_upsert.go
  plugin/testing_write.go
  plugin/testing_write_insert.go
  schema/testdata.go
  schema/testdata_test.go
  serve/destination_v1_test.go
Labels: automerge, fix

#1018 fix: Add backward compatibility for batch_size
  internal/servers/destination/v1/destinations.go
Labels: automerge, fix

#1020 fix(writers): Allow zero timeout, remove unused timeout options from mixedbatchwriter
  writers/batchwriter/batchwriter.go
  writers/mixedbatchwriter/mixedbatchwriter.go
  writers/streamingbatchwriter/mocktimer_test.go
  writers/streamingbatchwriter/streamingbatchwriter.go
  writers/streamingbatchwriter/streamingbatchwriter_test.go
Labels: automerge, fix

#1017 feat: Use named message slice types in writers
  message/write_message.go
  writers/batchwriter/batchwriter.go
  writers/batchwriter/batchwriter_test.go
  writers/mixedbatchwriter/mixedbatchwriter.go
  writers/mixedbatchwriter/mixedbatchwriter_test.go
Labels: automerge, feat

#1013 fix(writers): Don't export defaults
  writers/batchwriter/batchwriter.go
  writers/mixedbatchwriter/mixedbatchwriter.go
  writers/streamingbatchwriter/streamingbatchwriter.go
  writers/writers.go
Labels: automerge, fix

#1023 fix: Enable double migration test
  plugin/testing_write_migrate.go
Labels: automerge, fix

#1002 fix: Put null helpers back
  plugin/nulls.go
  plugin/testing_write.go
Labels: automerge, fix

#1026 fix: Update to plugin-pb v1.5.0
  go.mod
  go.sum
  internal/memdb/memdb.go
  internal/servers/destination/v0/destinations.go
  internal/servers/destination/v1/destinations.go
  internal/servers/plugin/v3/plugin.go
  message/write_message.go
  plugin/testing_write_delete.go
  writers/batchwriter/batchwriter.go
  writers/mixedbatchwriter/mixedbatchwriter_test.go
Labels: automerge, fix, priority merge

#1027 feat: Implement plugin Read
  internal/clients/state/v3/state.go
  internal/servers/plugin/v3/plugin.go
  plugin/plugin.go
  plugin/plugin_destination.go
Labels: automerge, feat

#1029 chore: Try larger runners
  .github/workflows/unittest.yml
Labels: ignore-for-release
