Repository cloudquery/plugin-sdk, pull requests merged in 2023-03, with the labels that each got.

#712 feat: Deterministic _cq_id
  plugins/source/plugin_test.go
  plugins/source/scheduler_dfs.go
  schema/meta.go
  schema/resource.go
  schema/resource_test.go
  specs/source.go
Labels: automerge, feat

#709 fix(pk): Skip filter for no PK
  plugins/destination/managed_writer.go
Labels: automerge, fix

#723 feat(multiplex): Detect duplicated clients
  plugins/source/scheduler_dfs.go
Labels: automerge, feat

#714 fix(types-json): Disable HTML escaping during JSON marshalling
  schema/json.go
  schema/json_test.go
Labels: automerge, fix

#716 fix(types-timestamp): Ensure timestamp is UTC
  schema/timestamptz.go
Labels: automerge, fix

#724 feat: Add arrow support for timestamp and bytea
  schema/bytea.go
  schema/resource_test.go
  schema/timestamptz.go
  testdata/testdata.go
Labels: automerge, feat

#726 feat(source): Expose docs generation
  clients/source/v1/source.go
  cloudquery/source/v1/source.proto
  internal/pb/source/v1/source.pb.go
  internal/pb/source/v1/source_grpc.pb.go
  internal/servers/source/v1/source.go
Labels: automerge, feat

#729 feat: Add ability to store table titles and render them in documentation
  caser/caser.go
  caser/caser_test.go
  plugins/source/.snapshots/TestGeneratePluginDocs-JSON-__tables.json
  plugins/source/.snapshots/TestGeneratePluginDocs-Markdown-incremental_table.md
  plugins/source/.snapshots/TestGeneratePluginDocs-Markdown-relation_relation_table_a.md
  plugins/source/.snapshots/TestGeneratePluginDocs-Markdown-relation_relation_table_b.md
  plugins/source/.snapshots/TestGeneratePluginDocs-Markdown-relation_table.md
  plugins/source/.snapshots/TestGeneratePluginDocs-Markdown-test_table.md
  plugins/source/docs.go
  plugins/source/options.go
  plugins/source/plugin.go
  plugins/source/templates/table.md.go.tpl
  schema/table.go
Labels: automerge, feat

#731 chore(docs): Add issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: automerge, ignore-for-release

#732 feat: Support for User Specifying Primary Key Scheme (default or cq-ids)
  internal/memdb/memdb_test.go
  plugins/destination/plugin.go
  plugins/destination/plugin_test.go
  plugins/destination/plugin_testing.go
  plugins/destination/plugin_testing_migrate.go
  schema/table.go
  specs/destination.go
  specs/pk_mode.go
  specs/pk_mode_test.go
Labels: automerge, feat

#739 fix(transform): Use path instead of field name for PK options
  transformers/struct.go
  transformers/struct_test.go
Labels: automerge, fix
