Repository cloudquery/plugin-sdk, pull requests merged in 2023-01, with the labels that each got.

#536 fix: Managed writer log message, timeout->flush
  plugins/destination/managed_writer.go
Labels: automerge, fix

#560 chore: Fix Vale ignore path
  .github/workflows/lint_markdown.yml
Labels: automerge, ignore-for-release

#561 fix(testing): Sort results before comparison in tests
  plugins/destination/plugin_testing.go
Labels: automerge, fix

#563 feat: Add primary key validation
  plugins/source/scheduler_dfs.go
  schema/bool.go
  schema/bytea.go
  schema/cidr.go
  schema/cidr_array.go
  schema/float8.go
  schema/inet.go
  schema/inet_array.go
  schema/int8.go
  schema/int8_array.go
  schema/json.go
  schema/macaddr.go
  schema/macaddr_array.go
  schema/resource.go
  schema/text.go
  schema/text_array.go
  schema/timestamptz.go
  schema/types.go
  schema/uuid.go
  schema/uuid_array.go
Labels: automerge, feat

#565 fix(testing): Some fixes to the ordering for plugin tests
  plugins/destination/plugin_testing.go
Labels: automerge, fix

#567 fix(testing): Fix bug in testing missed due to reference to resource being re-used in memdb
  plugins/destination/plugin_testing.go
Labels: automerge, fix

#564 feat: Add Transformer for tables (codegen replacement)
  plugins/source/plugin.go
  schema/table.go
  transformers/struct.go
Labels: automerge, feat

#570 feat: Support conversion of Unix timestamps in timestamptz
  schema/timestamptz.go
  schema/timestamptz_test.go
Labels: automerge, feat

#545 feat: Add scheduler option and introduce Round Robin scheduler
  plugins/source/benchmark_test.go
  plugins/source/plugin.go
  plugins/source/plugin_test.go
  plugins/source/scheduler.go
  plugins/source/scheduler_dfs.go
  plugins/source/scheduler_round_robin.go
  plugins/source/scheduler_round_robin_test.go
  specs/scheduler.go
  specs/scheduler_test.go
  specs/source.go
  specs/source_test.go
Labels: feat

#573 feat: Add unwrap option to transformations
  transformers/struct.go
  transformers/struct_test.go
Labels: automerge, feat

#575 feat(transformers): Add WithTypeTransformer
  transformers/struct.go
Labels: automerge, feat

#574 feat(testing): Add test for migrations
  plugins/destination/plugin_testing.go
Labels: automerge, feat

#579 feat: Add WithIgnoreInTestsTransformer
  transformers/struct.go
Labels: automerge, feat

#578 feat: Add WithResolverTransformer
  transformers/struct.go
Labels: automerge, feat

#510 feat: Add size in bytes to CQ types
  schema/bool.go
  schema/bytea.go
  schema/bytea_test.go
  schema/cidr.go
  schema/cidr_array.go
  schema/cidr_array_test.go
  schema/float8.go
  schema/float8_test.go
  schema/inet.go
  schema/inet_array.go
  schema/inet_array_test.go
  schema/int8.go
  schema/int8_array.go
  schema/int8_array_test.go
  schema/json.go
  schema/json_test.go
  schema/macaddr.go
  schema/macaddr_array.go
  schema/macaddr_test.go
  schema/text.go
  schema/text_array.go
  schema/text_array_test.go
  schema/timestamptz.go
  schema/types.go
  schema/uuid.go
  schema/uuid_array.go
  schema/uuid_array_test.go
Labels: automerge, feat

#582 feat: Add batch size bytes as additional option
  internal/memdb/memdb_test.go
  plugins/destination/managed_writer.go
  plugins/destination/plugin.go
  specs/destination.go
  specs/destination_test.go
  specs/spec_reader.go
Labels: automerge, feat

#569 feat: Add local backend for storing cursor state
  backend/backend.go
  codegen/table.go
  codegen/templates/column.go.tpl
  codegen/templates/table.go.tpl
  internal/backends/local/local.go
  internal/backends/local/local_test.go
  internal/backends/local/spec.go
  plugins/source/.snapshots/TestGeneratePluginDocs-JSON-__tables.json
  plugins/source/.snapshots/TestGeneratePluginDocs-Markdown-README.md
  plugins/source/.snapshots/TestGeneratePluginDocs-Markdown-incremental_table.md
  plugins/source/.snapshots/TestGenerateSourcePluginDocs-JSON-__tables.json
  plugins/source/.snapshots/TestGenerateSourcePluginDocs-Markdown-README.md
  plugins/source/.snapshots/TestGenerateSourcePluginDocs-Markdown-relation_relation_table.md
  plugins/source/.snapshots/TestGenerateSourcePluginDocs-Markdown-relation_table.md
  plugins/source/.snapshots/TestGenerateSourcePluginDocs-Markdown-test_table.md
  plugins/source/docs.go
  plugins/source/docs_test.go
  plugins/source/plugin.go
  plugins/source/plugin_test.go
  plugins/source/templates/all_tables_entry.md.go.tpl
  plugins/source/templates/table.md.go.tpl
  schema/column.go
  schema/table.go
  serve/source_test.go
  specs/backend.go
  specs/backend_test.go
  specs/source.go
Labels: automerge, feat

#589 feat: Remove codegen
  codegen/.snapshots/TestGenerateTemplate-should_add_comma_between_relations
  codegen/.snapshots/TestGenerateTemplate-should_add_ignore_in_tests_to_columns
  codegen/column.go
  codegen/doc.go
  codegen/options.go
  codegen/table.go
  codegen/table_test.go
  codegen/template.go
  codegen/template_test.go
  codegen/templates/column.go.tpl
  codegen/templates/table.go.tpl
  codegen/transformers.go
  codegen/unwrap.go
  codegen/util.go
  transformers/struct.go
Labels: automerge, feat

#592 fix: Sentry errors not sent
  plugins/source/scheduler.go
  plugins/source/scheduler_dfs.go
  schema/bool.go
  schema/bytea.go
  schema/cidr_array.go
  schema/errors.go
  schema/float8.go
  schema/inet.go
  schema/inet_array.go
  schema/int8.go
  schema/int8_array.go
  schema/json.go
  schema/macaddr.go
  schema/macaddr_array.go
  schema/text.go
  schema/text_array.go
  schema/timestamptz.go
  schema/uuid.go
  schema/uuid_array.go
Labels: automerge, fix

#599 feat(docs): Sort tables
  plugins/source/.snapshots/TestGeneratePluginDocs-JSON-__tables.json
  plugins/source/.snapshots/TestGeneratePluginDocs-Markdown-README.md
  plugins/source/.snapshots/TestGeneratePluginDocs-Markdown-relation_relation_table_a.md
  plugins/source/.snapshots/TestGeneratePluginDocs-Markdown-relation_relation_table_b.md
  plugins/source/.snapshots/TestGeneratePluginDocs-Markdown-relation_table.md
  plugins/source/docs.go
  plugins/source/docs_test.go
  plugins/source/templates/all_tables.md.go.tpl
Labels: automerge, feat

#595 feat(transformers): Add support for `net.IP`
  transformers/struct.go
  transformers/struct_test.go
Labels: automerge, feat

#603 fix: Change options for new client
  clients/destination.go
  clients/destination_test.go
  internal/memdb/memdb_test.go
  internal/pb/destination.pb.go
  internal/pb/destination.proto
  internal/servers/destinations.go
  plugins/destination/managed_writer.go
  plugins/destination/plugin.go
  plugins/destination/plugin_testing.go
  plugins/destination/unmanaged_writer.go
  plugins/source/plugin.go
  plugins/source/plugin_test.go
  schema/table.go
  serve/destination_test.go
  serve/source_test.go
  specs/backend.go
  specs/source.go
Labels: automerge, fix

#607 fix: PK Addition Order
  plugins/source/plugin.go
  plugins/source/plugin_test.go
Labels: automerge, fix

#604 feat(destinations): Add `migrate_mode`
  specs/destination.go
  specs/destination_test.go
  specs/migrate_mode.go
  specs/migrate_mode_test.go
  specs/write_mode.go
  specs/write_mode_test.go
Labels: feat

#606 fix(destination): Pass proper spec to client constructor
  internal/memdb/memdb_test.go
  plugins/destination/plugin.go
Labels: automerge, fix

#609 feat(spec): Add source, destination String methods
  specs/destination.go
  specs/destination_test.go
  specs/source.go
  specs/source_test.go
Labels: automerge, feat

#617 fix: Simplify client naming conventions
  clients/destination/v0/destination.go
  clients/destination/v0/destination_test.go
  clients/source/v0/source.go
  clients/source/v0/source_test.go
  clients/source/v1/source.go
  serve/destination_v0_test.go
  serve/source_v0_test.go
  serve/source_v1_test.go
Labels: automerge, fix

#611 fix(clients): Update `log line too long` message
  clients/destination/v0/destination.go
  clients/source/v0/source.go
  internal/logging/log_reader.go
  internal/logging/log_reader_test.go
Labels: automerge, fix

#619 feat: Add version discovery service
  Makefile
  clients/discovery/v0/constants.go
  clients/discovery/v0/discovery.go
  clients/discovery/v0/terminate.go
  clients/discovery/v0/terminate_windows.go
  clients/source/v1/source.go
  cloudquery/discovery/v0/discovery.proto
  internal/pb/discovery/v0/discovery.pb.go
  internal/pb/discovery/v0/discovery_grpc.pb.go
  internal/servers/destination/v0/destinations.go
  internal/servers/discovery/v0/discovery.go
  serve/destination.go
  serve/source.go
Labels: automerge, feat

#616 feat: Add NopBackend
  internal/backends/nop/nop.go
  plugins/source/plugin.go
  specs/backend.go
Labels: automerge, feat

#618 chore(test): Add overwrite + migrate destination plugin test
  plugins/destination/plugin_testing.go
Labels: automerge, ignore-for-release

#621 chore: Add gopkg.dev and goreportcard badges to README
  README.md
Labels: automerge, ignore-for-release

#625 fix: Ignore env variables in comments
  specs/spec_reader.go
  specs/spec_reader_test.go
  specs/testdata/env_variable_in_string.yml
  specs/testdata/env_variables.yml
Labels: automerge, fix

#630 fix: Only call `newExecutionClient` if needed
  plugins/source/plugin.go
Labels: automerge, fix

#629 feat(destination): Filter the duplicate primary keys prior to writing batch
  internal/pk/pk.go
  internal/pk/pk_test.go
  plugins/destination/managed_writer.go
Labels: automerge, feat

#623 chore(ci): Add codecov
  .github/workflows/unittest.yml
Labels: automerge, ignore-for-release

#633 fix: Add cq-dir param to discovery
  clients/discovery/v0/discovery.go
Labels: automerge, fix

#635 chore: Revert "fix: Add cq-dir param to discovery"
  clients/discovery/v0/discovery.go
Labels: automerge, ignore-for-release

#636 feat: Return error message when download fails
  registry/download.go
Labels: automerge, feat

#632 feat: Support downloading plugins from other cloudquery repos
  registry/download.go
  registry/download_test.go
Labels: automerge, feat

#639 chore(sentry): Report table name in the pk issue
  plugins/destination/managed_writer.go
Labels: automerge, ignore-for-release
