Repository cloudquery/plugin-sdk, pull requests merged in 2023-11, with the labels that each got.

#1354 fix: Return clearer error when team name empty or not set
  premium/usage.go
Labels: automerge, fix

#1361 chore: Typos in comments
  schema/resource.go
  writers/batchwriter/batchwriter.go
Labels: automerge, ignore-for-release

#1366 fix: Mark relations as paid as well
  premium/tables.go
  premium/tables_test.go
Labels: automerge, fix

#1374 fix: Batching for mixedbatchwriter
  writers/mixedbatchwriter/mixedbatchwriter.go
Labels: automerge, fix

#1372 fix: Retrieve team for api key
  examples/simple_plugin/go.sum
  premium/usage.go
Labels: automerge, fix

#1387 feat: Improved tracing
  examples/simple_plugin/go.mod
  examples/simple_plugin/go.sum
  go.mod
  go.sum
  scheduler/scheduler_dfs.go
  serve/opentelemetry.go
Labels: automerge, feat

#1386 fix: Cleanup batch writers
  writers/batchwriter/batchwriter.go
  writers/streamingbatchwriter/streamingbatchwriter.go
Labels: automerge, fix

#1389 chore: Upgrade golangci-lint to 1.55.2
  .github/workflows/lint_golang.yml
  .golangci.yml
Labels: automerge, ignore-for-release
