Repository cloudquery/plugin-sdk, pull requests merged in 2023-04, with the labels that each got.

#761 feat: Add JSON UnmarshalOne
  types/json.go
  types/json_test.go
Labels: feat

#762 feat: Add ValueString methods
  types/inet.go
  types/json.go
  types/mac.go
  types/uuid.go
Labels: feat

#763 fix: Refactor GenTestData to take options struct, add null values to test data
  internal/memdb/memdb_test.go
  plugins/destination/plugin_testing_migrate.go
  plugins/destination/plugin_testing_overwrite.go
  plugins/destination/plugin_testing_overwrite_delete_stale.go
  plugins/destination/plugin_testing_write_append.go
  testdata/testdata.go
Labels: fix

#765 feat: Null rows should go second
  testdata/testdata.go
Labels: feat

#770 feat: Bump sdk to v2
  Makefile
  clients/destination/v0/destination.go
  clients/destination/v0/destination_test.go
  clients/discovery/v0/discovery.go
  clients/source/v0/source.go
  clients/source/v0/source_test.go
  clients/source/v1/source.go
  cloudquery/base/v0/base.proto
  cloudquery/destination/v0/destination.proto
  cloudquery/discovery/v0/discovery.proto
  cloudquery/source/v0/source.proto
  cloudquery/source/v1/source.proto
  go.mod
  go.sum
  internal/backends/local/local.go
  internal/backends/local/local_test.go
  internal/deprecated/testing.go
  internal/memdb/memdb.go
  internal/memdb/memdb_test.go
  internal/pb/destination/v0/destination.pb.go
  internal/pb/destination/v0/destination_grpc.pb.go
  internal/pb/source/v0/source.pb.go
  internal/pb/source/v0/source_grpc.pb.go
  internal/pk/pk.go
  internal/servers/destination/v0/destinations.go
  internal/servers/discovery/v0/discovery.go
  internal/servers/source/v0/source.go
  internal/servers/source/v1/source.go
  plugins/destination/managed_writer.go
  plugins/destination/plugin.go
  plugins/destination/plugin_testing.go
  plugins/destination/plugin_testing_migrate.go
  plugins/destination/plugin_testing_overwrite.go
  plugins/destination/plugin_testing_overwrite_delete_stale.go
  plugins/destination/plugin_testing_write_append.go
  plugins/destination/reverse_transformer.go
  plugins/destination/unmanaged_writer.go
  plugins/source/benchmark_test.go
  plugins/source/docs.go
  plugins/source/docs_test.go
  plugins/source/metrics.go
  plugins/source/options.go
  plugins/source/plugin.go
  plugins/source/plugin_test.go
  plugins/source/scheduler.go
  plugins/source/scheduler_dfs.go
  plugins/source/scheduler_round_robin.go
  plugins/source/scheduler_round_robin_test.go
  plugins/source/testing.go
  schema/arrow.go
  schema/meta.go
  schema/table.go
  serve/destination.go
  serve/destination_v0_test.go
  serve/source.go
  serve/source_v0_test.go
  serve/source_v1_test.go
  testdata/testdata.go
  transformers/struct.go
  transformers/struct_test.go
Labels: feat

#771 chore(md): Update `README.md` with `v2` links
  README.md
Labels: automerge, ignore-for-release

#777 fix(unimplemented): Conform to the interface
  plugins/destination/plugin.go
Labels: automerge, fix

#778 feat(destination): Remove redundant `ReverseTransformValues` method
  internal/memdb/memdb.go
  plugins/destination/plugin.go
  plugins/destination/reverse_transformer.go
Labels: automerge, feat

#776 feat(ci): Set up releases for v1
  .github/workflows/release-pr.yml
Labels: automerge, feat

#775 fix: Backport deterministic cq_id fix to v1
  plugins/source/plugin_test.go
  schema/resource.go
Labels: automerge, fix

#774 fix: Handle When `_cq_id` only PK
  plugins/source/plugin_test.go
  schema/resource.go
Labels: automerge, fix

#783 fix: Add StableTime to GenTestDataOptions and make panic message more verbose
  plugins/destination/plugin_testing.go
  testdata/testdata.go
Labels: fix

#768 fix: Add composite PK to test table
  testdata/testdata.go
Labels: automerge, fix

#784 feat: Use ApproxEqual in dest tests
  go.mod
  go.sum
  internal/servers/destination/v0/destinations.go
  plugins/destination/plugin_testing_migrate.go
  plugins/destination/plugin_testing_overwrite.go
  plugins/destination/plugin_testing_overwrite_delete_stale.go
  plugins/destination/plugin_testing_write_append.go
  schema/arrow.go
  testdata/testdata.go
Labels: automerge, feat

#786 fix: Make cq_id unique for backward compat
  internal/servers/destination/v0/destinations.go
Labels: automerge, fix

#788 fix: Destination testing memory leak
  internal/memdb/memdb.go
  plugins/destination/plugin_testing.go
  plugins/destination/plugin_testing_migrate.go
  plugins/destination/plugin_testing_overwrite.go
  plugins/destination/plugin_testing_overwrite_delete_stale.go
  plugins/destination/plugin_testing_write_append.go
Labels: automerge, fix

#790 feat: Change default source tables to none
  specs/source.go
  specs/source_test.go
Labels: automerge, feat

#792 fix: Update to latest Arrow (cqmain branch)
  go.mod
  go.sum
Labels: automerge, fix

#793 fix: Set _cq_id to NotNull in destinations for backward compat
  internal/servers/destination/v0/destinations.go
Labels: automerge, fix

#797 fix: Disallow null character in strings per utf8 spec
  schema/arrow.go
Labels: automerge, fix

#795 fix: Arrow Retain and Release fixes
  internal/servers/destination/v0/destinations.go
  plugins/destination/managed_writer.go
Labels: fix

#799 fix: Make cq_id non required on destination
  plugins/destination/plugin.go
Labels: automerge, fix

#801 fix: Undo release of all resources in managed writer
  plugins/destination/managed_writer.go
Labels: automerge, fix

#803 chore: Run tests with -tags=assert
  .github/workflows/unittest.yml
  Makefile
Labels: automerge, ignore-for-release

#806 fix: Truncate timestamp to millisecond in dest testing
  testdata/testdata.go
Labels: automerge, fix

#808 fix: Release resource on SkipSecondAppend
  plugins/destination/plugin_testing_write_append.go
Labels: automerge, fix

#811 fix(testdata): Add old style gen testdata
  testdata/testdata.go
Labels: automerge, fix

#810 fix: Use Go memory allocator for arrow
  internal/memdb/memdb.go
  internal/memdb/memdb_test.go
  plugins/destination/plugin_testing.go
  plugins/destination/plugin_testing_migrate.go
  plugins/destination/plugin_testing_overwrite.go
  plugins/destination/plugin_testing_overwrite_delete_stale.go
  plugins/destination/plugin_testing_write_append.go
  testdata/testdata.go
Labels: automerge, fix

#812 chore(testdata): Deprecation notice
  testdata/testdata.go
Labels: automerge, ignore-for-release

#796 fix: Fail on empty tables
  specs/source.go
  specs/source_test.go
  specs/spec_reader_test.go
  specs/testdata/dir/aws.yml
  specs/testdata/dir_yaml/aws.yaml
  specs/testdata/env_variable_in_string.yml
  specs/testdata/env_variables.yml
  specs/testdata/gcp.yml
  specs/testdata/gcpv2.yml
  specs/testdata/multiple_sources.yml
  specs/testdata/numbers.yml
Labels: automerge, fix

#814 fix(testing): Add sorting for testing dest migrations
  plugins/destination/plugin_testing.go
  plugins/destination/plugin_testing_migrate.go
  plugins/destination/plugin_testing_overwrite.go
  plugins/destination/plugin_testing_overwrite_delete_stale.go
  plugins/destination/plugin_testing_write_append.go
  testdata/testdata.go
Labels: automerge, fix

#785 chore(testing): Move `.snapshots` to `testdata`
  .github/workflows/lint_markdown.yml
  plugins/source/docs_test.go
  plugins/source/testdata/TestGeneratePluginDocs-JSON-__tables.json
  plugins/source/testdata/TestGeneratePluginDocs-Markdown-README.md
  plugins/source/testdata/TestGeneratePluginDocs-Markdown-incremental_table.md
  plugins/source/testdata/TestGeneratePluginDocs-Markdown-relation_relation_table_a.md
  plugins/source/testdata/TestGeneratePluginDocs-Markdown-relation_relation_table_b.md
  plugins/source/testdata/TestGeneratePluginDocs-Markdown-relation_table.md
  plugins/source/testdata/TestGeneratePluginDocs-Markdown-test_table.md
Labels: automerge, ignore-for-release

#817 feat(arrow): Pretty-print field changes
  schema/arrow.go
  schema/arrow_test.go
Labels: automerge, feat

#820 fix: TransformWithStruct/DefaultNameTransformer change for invalid column names
  schema/table.go
  transformers/struct.go
  transformers/struct_test.go
Labels: automerge, fix

#824 feat: Add table description to Arrow schema metadata
  schema/arrow.go
Labels: automerge, feat

#823 feat(arrow): Streamline Apache Arrow extension types
  go.mod
  go.sum
  plugins/destination/plugin_testing_overwrite.go
  plugins/destination/plugin_testing_overwrite_delete_stale.go
  schema/arrow.go
  testdata/testdata.go
  types/inet.go
  types/inet_test.go
  types/json.go
  types/json_test.go
  types/mac.go
  types/uuid.go
Labels: automerge, feat

#827 feat(test): Add double migration test
  plugins/destination/plugin_testing_migrate.go
Labels: automerge, feat

#825 feat: Time values are truncated uniformly
  clients/destination/v0/destination.go
Labels: automerge, feat

#821 chore(issue-templates): Remove needs-triage label from issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: automerge, ignore-for-release

#828 fix(transformer): Allow camel-cased json tags
  transformers/struct.go
  transformers/struct_test.go
Labels: automerge, fix

#822 fix: Destination migration testing using incorrect mode
  plugins/destination/plugin_testing.go
Labels: automerge, fix

#816 chore(ci): Add timeout to CI jobs
  .github/workflows/add_tags.yml
  .github/workflows/lint_golang.yml
  .github/workflows/lint_markdown.yml
  .github/workflows/pr_title.yml
  .github/workflows/release-pr.yml
  .github/workflows/unittest-post.yml
  .github/workflows/unittest.yml
Labels: automerge, ignore-for-release

#834 chore(tests): Validate the unescaped data stored as escaped
  types/json.go
  types/json_test.go
Labels: automerge, ignore-for-release
