Repository cloudquery/plugin-sdk, pull requests merged in 2024-02, with the labels that each got.

#1517 feat: Support offline licensing for all plugins from a specific team
  premium/offline.go
  premium/offline_test.go
Labels: feat

#1521 feat: Implement `GetSpecSchema` call
  internal/servers/plugin/v3/plugin.go
Labels: automerge, feat

#1522 chore: Revert toolchain update
  examples/simple_plugin/go.mod
  go.mod
Labels: ignore-for-release

#1531 fix: Default Plugin logger assumes plugin is a `source`
  plugin/plugin.go
Labels: automerge, fix

#1530 fix: Support list scalars from JSON
  scalar/list.go
  scalar/list_test.go
  scheduler/scheduler.go
Labels: automerge, fix

#1533 feat: Allow homogeneous data types to be configured
  plugin/testing_write.go
  plugin/testing_write_delete.go
  plugin/testing_write_insert.go
  plugin/testing_write_migrate.go
  plugin/testing_write_upsert.go
  schema/testdata.go
Labels: automerge, feat

#1536 feat: Skip table validation during init
  plugin/plugin.go
  plugin/validate.go
Labels: automerge, feat

#1537 fix: Remove unreachable code
  serve/package.go
Labels: automerge, fix
