Repository cloudquery/plugin-sdk, pull requests merged in 2024-06, with the labels that each got.

#1723 feat: Add batching for source plugins
  internal/batch/slice_test.go
  scalar/binary.go
  scalar/bool.go
  scalar/date32.go
  scalar/date64.go
  scalar/decimal.go
  scalar/duration.go
  scalar/float.go
  scalar/inet.go
  scalar/int.go
  scalar/interval.go
  scalar/json.go
  scalar/list.go
  scalar/mac.go
  scalar/scalar.go
  scalar/string.go
  scalar/struct.go
  scalar/time.go
  scalar/timestamp.go
  scalar/uint.go
  scalar/uuid.go
  scheduler/batch.go
  scheduler/benchmark_test.go.backup
  scheduler/scheduler.go
  scheduler/scheduler_test.go
Labels: feat

#1725 refactor: Split `transformers/struct.go`
  transformers/ignore_in_tests.go
  transformers/name.go
  transformers/options.go
  transformers/resolver.go
  transformers/struct.go
  transformers/type.go
Labels: automerge, refactor

#1724 feat: Remove plugin option for logging error events to Sentry
  examples/simple_plugin/go.mod
  examples/simple_plugin/go.sum
  go.mod
  go.sum
  internal/servers/plugin/v3/plugin.go
  scheduler/scheduler.go
  scheduler/scheduler_dfs.go
  serve/plugin.go
Labels: feat

#1720 fix: Don't include other relation siblings if not specified in config
  schema/table.go
  schema/table_test.go
Labels: automerge, fix

#1740 fix: Remove no sentry deprecation warning
  serve/plugin.go
Labels: automerge, fix

#1746 fix: Revert "fix: Allow marshaling plain string values into JSON scalars"
  scalar/errors.go
  scalar/json.go
  scalar/json_test.go
Labels: automerge, fix

#1742 fix: Send parent in migrate message
  scheduler/scheduler.go
Labels: automerge, fix

#1719 fix: Account for bytes limit properly when batching records for writing
  internal/batch/cap.go
  internal/batch/slice.go
  internal/batch/slice_test.go
  writers/batchwriter/batchwriter.go
  writers/batchwriter/batchwriter_test.go
  writers/mixedbatchwriter/mixedbatchwriter.go
  writers/streamingbatchwriter/streamingbatchwriter.go
Labels: automerge, fix

#1642 feat: Batch resources into a single record on source side
  scheduler/batch.go
  scheduler/benchmark_test.go.backup
  scheduler/scheduler.go
  scheduler/scheduler_test.go
Labels: automerge, feat

#1760 chore: Update CODEOWNERS
  CODEOWNERS
Labels: ignore-for-release

#1757 feat: Add `duration_ms` to `table sync finished` log message
  scheduler/metrics.go
  scheduler/scheduler.go
  scheduler/scheduler_dfs.go
Labels: automerge, feat

#1766 fix: Use Atomic Pointer for updating duration metric
  scheduler/metrics.go
  scheduler/scheduler.go
  scheduler/scheduler_dfs.go
Labels: automerge, fix

#1771 feat: Enable batching resources on source side by default
  scheduler/batch.go
  scheduler/scheduler.go
  scheduler/scheduler_test.go
Labels: automerge, feat

#1751 feat: Better OTEL traces, add metrics
  examples/simple_plugin/go.mod
  examples/simple_plugin/go.sum
  go.mod
  go.sum
  internal/servers/plugin/v3/plugin.go
  plugin/plugin_source.go
  scheduler/metrics.go
  scheduler/scheduler.go
  scheduler/scheduler_dfs.go
  serve/opentelemetry.go
  serve/plugin.go
Labels: automerge, feat
