Repository cloudquery/plugin-sdk, pull requests merged in 2024-05, with the labels that each got.

#1672 fix: Expose IncreaseForTable on UsageClient interface
  premium/usage.go
Labels: automerge, fix

#1677 feat: Re-configure batch updater using response headers
  premium/usage.go
  premium/usage_test.go
Labels: automerge, feat

#1680 fix: Correct error message on Read failure
  internal/servers/plugin/v3/plugin.go
Labels: fix

#1647 fix: Properly handle records with multiple rows in batching
  writers/batchwriter/batchwriter.go
  writers/batchwriter/batchwriter_test.go
  writers/mixedbatchwriter/mixedbatchwriter.go
  writers/streamingbatchwriter/streamingbatchwriter.go
  writers/streamingbatchwriter/streamingbatchwriter_test.go
Labels: automerge, fix

#1685 fix: Remove JSON schema validation warnings
  plugin/plugin.go
Labels: automerge, fix

#1700 feat: Enable `NewConnectedClientWithOptions` to set `ClientOptions`
  state/client.go
Labels: automerge, feat

#1702 chore: Code style in state
  internal/clients/state/v3/state.go
  state/client.go
Labels: automerge, ignore-for-release

#1705 fix: Added support for list pointers
  scalar/list.go
  scalar/list_test.go
Labels: fix
