Repository cloudquery/plugin-sdk, pull requests merged in 2024-08, with the labels that each got.

#1844 feat: Allow setting JSON type schema max depth
  transformers/options.go
  transformers/struct.go
  transformers/struct_test.go
Labels: automerge, feat

#1849 chore: Add more govet lint rules
  .golangci.yml
  internal/servers/destination/v0/schemav2tov3.go
Labels: automerge

#1770 feat: Support AWS usage marketplace
  examples/simple_plugin/go.mod
  examples/simple_plugin/go.sum
  go.mod
  go.sum
  premium/mocks/marketplacemetering.go
  premium/usage.go
  premium/usage_test.go
Labels: automerge, feat

#1867 chore: Rename scheduler_tezt.go to scheduler_debug.go
  scheduler/scheduler_debug.go
Labels: automerge, ignore-for-release

#1866 feat: Add RemoteOAuth Token helper to refresh `access_token` from cloud environment
  go.mod
  go.sum
  helpers/remoteoauth/token.go
  helpers/remoteoauth/token_test.go
  helpers/remoteoauth/tokenoptions.go
  helpers/remoteoauth/tokenoptions_test.go
Labels: automerge, feat

#1875 feat: Add remoteoauth helpers (`TokenAuthTransport` and `TokenAuthEditor`)
  helpers/remoteoauth/tokenautheditor.go
  helpers/remoteoauth/tokenauthtransport.go
Labels: automerge, feat

#1878 feat: Add warning on duplicate clients for `round-robin` and `shuffle` schedulers
  scheduler/scheduler_round_robin.go
  scheduler/scheduler_shuffle.go
Labels: automerge, feat
