Repository cloudquery/plugin-sdk, pull requests merged in 2024-12, with the labels that each got.

#1996 fix: Handle integer overflow
  configtype/time.go
Labels: automerge, fix

#1995 feat: Implement batch sender.
  scheduler/batchsender/batch_sender.go
  scheduler/scheduler_dfs.go
Labels: automerge, feat

#2012 fix: OpenTelemetry schema URL panic
  serve/opentelemetry.go
Labels: automerge, fix

#2013 chore: Use the same otel resource for LoggerProvider as for others
  serve/opentelemetry.go
Labels: automerge, ignore-for-release

#2011 fix: Use field name in json type schema if json tag is missing
  transformers/name.go
  transformers/options.go
  transformers/struct.go
  transformers/struct_test.go
Labels: automerge, fix

#2037 fix: Validate missing PK components
  schema/resource.go
  schema/resource_test.go
Labels: automerge, fix
