Repository cloudquery/plugin-sdk, pull requests merged in 2024-07, with the labels that each got.

#1777 fix: Reuse builders on state client flush
  internal/clients/state/v3/state.go
Labels: automerge, fix

#1788 fix: Properly handle relational tables metrics
  scheduler/metrics.go
Labels: automerge, fix

#1791 fix: Log OTEL errors as warning level instead of debug
  serve/opentelemetry.go
Labels: automerge, fix

#1800 feat: Implement transformations logic.
  examples/simple_plugin/plugin/client.go
  internal/memdb/memdb.go
  internal/reversertransformer/reversertransformer.go
  internal/reversertransformer/reversertransformer_test.go
  internal/servers/plugin/v3/plugin.go
  plugin/plugin.go
  plugin/plugin_test.go
  plugin/plugin_transformer.go
Labels: automerge, feat

#1803 fix: Use trace level for source batcher log message
  scheduler/batch.go
Labels: automerge

#1807 feat: Send plugin logs via OTEL
  examples/simple_plugin/go.mod
  examples/simple_plugin/go.sum
  go.mod
  go.sum
  serve/opentelemetry.go
  serve/plugin.go
Labels: automerge, feat

#1796 feat: Add JSON type schema
  schema/arrow.go
  schema/column.go
  serve/package.go
  transformers/struct.go
  transformers/struct_test.go
Labels: automerge, feat

#1816 fix: Don't panic when trying `ToSnake` on `s` character
  caser/caser.go
  caser/caser_test.go
Labels: automerge, fix

#1819 fix: Reduce JSON column schema nesting
  transformers/struct.go
  transformers/struct_test.go
Labels: automerge, fix

#1817 fix: Properly handle map and slice pointers
  transformers/struct.go
  transformers/struct_test.go
Labels: automerge, fix

#1821 feat: Add `zerolog.Logger` to `retryablehttp.LeveledLogger` adapter struct
  go.mod
  helpers/retryablehttp/logger.go
Labels: automerge, feat

#1824 fix: Don't include non exported fields or ignored types in JSON schema
  transformers/struct.go
  transformers/struct_test.go
Labels: automerge, fix

#1828 feat: Add PluginKind "transformer".
  plugin/plugin_package.go
Labels: automerge, feat

#1827 feat: Add `PermissionsNeeded` to tables schema
  internal/memdb/memdb.go
  schema/arrow.go
  schema/table.go
  schema/table_test.go
  serve/package.go
  serve/testdata/memdbtables.json
Labels: automerge, feat

#1835 fix: Handle commas in permissions array
  schema/table.go
  schema/table_test.go
Labels: automerge, fix

#1838 feat: Implement TransformSchema support.
  examples/simple_plugin/plugin/client.go
  internal/memdb/memdb.go
  internal/reversertransformer/reversertransformer.go
  internal/reversertransformer/reversertransformer_test.go
  internal/servers/plugin/v3/plugin.go
  internal/servers/plugin/v3/plugin_test.go
  plugin/plugin.go
  plugin/plugin_test.go
  plugin/plugin_transformer.go
Labels: automerge, feat
