Repository cloudquery/plugin-sdk, pull requests merged in 2024-09, with the labels that each got.

#1885 fix: Fix panic when converting schema changes to string
  schema/table.go
Labels: automerge, fix

#1889 feat: Support Contract Listing For AWS Marketplace
  examples/simple_plugin/go.mod
  examples/simple_plugin/go.sum
  go.mod
  go.sum
  premium/mocks/licensemanager.go
  premium/offline.go
  premium/offline_test.go
  serve/plugin.go
Labels: automerge, feat

#1891 feat: Add sync sharding
  examples/simple_plugin/go.mod
  examples/simple_plugin/go.sum
  go.mod
  go.sum
  internal/servers/plugin/v3/plugin.go
  plugin/plugin_source.go
  scheduler/scheduler.go
  scheduler/scheduler_debug.go
  scheduler/scheduler_dfs.go
  scheduler/scheduler_round_robin.go
  scheduler/scheduler_shuffle.go
  scheduler/scheduler_test.go
Labels: automerge, feat

#1898 feat(remoteoauth): Add `WithToken` option
  helpers/remoteoauth/token_test.go
  helpers/remoteoauth/tokenoptions.go
Labels: feat

#1900 feat: Add `opts.SchedulerOpts()` helper to convert `plugin.SyncOptions` for scheduler
  helpers/opts/syncoptions.go
Labels: feat

#1901 chore: Replace Discord links with the new community
  .github/ISSUE_TEMPLATE/config.yml
  CONTRIBUTING.md
Labels: automerge, ignore-for-release

#1907 feat: Update concurrency formula.
  scheduler/scheduler.go
Labels: feat
