Repository cloudquery/plugin-sdk, pull requests merged in 2024-10, with the labels that each got.

#1913 fix: Error handling in StreamingBatchWriter
  writers/streamingbatchwriter/streamingbatchwriter.go
  writers/streamingbatchwriter/streamingbatchwriter_test.go
Labels: automerge, fix

#1914 feat: Implement RandomQueue scheduler strategy
  scheduler/metrics/metrics.go
  scheduler/metrics/metrics_test.go
  scheduler/queue/active_work_signal.go
  scheduler/queue/concurrent_random_queue.go
  scheduler/queue/scheduler.go
  scheduler/queue/scheduler_test.go
  scheduler/queue/worker.go
  scheduler/resolvers/resolvers.go
  scheduler/scheduler.go
  scheduler/scheduler_debug.go
  scheduler/scheduler_dfs.go
  scheduler/scheduler_round_robin.go
  scheduler/scheduler_shuffle.go
  scheduler/scheduler_shuffle_queue.go
  scheduler/strategy.go
Labels: feat

#1920 fix(tests): WriterTestSuite.handleNulls should not overwrite columns
  plugin/nulls.go
Labels: automerge, fix

#1923 feat: Add time.Sleep to mitigate race condition.
  scheduler/queue/active_work_signal.go
Labels: feat

#1932 chore: Fix vale linter
  .github/workflows/lint_markdown.yml
Labels: automerge, ignore-for-release

#1938 feat: Make state client versioning the default, remove option
  internal/clients/state/v3/state.go
  serve/state_test.go
  state/client.go
Labels: automerge, feat

#1941 fix: Ensure module field exists in all log messages
  plugin/plugin.go
  serve/plugin.go
Labels: automerge, fix

#1905 feat: Add Time configtype
  configtype/time.go
  configtype/time_test.go
  configtype/util.go
  configtype/util_test.go
Labels: automerge, feat

#1947 fix: Flaky usage tests
  premium/usage.go
  premium/usage_test.go
Labels: automerge, fix

#1949 chore: BatchUpdater: Protect against unrealistic values
  premium/usage.go
Labels: ignore-for-release

#1948 feat: Support for quota query interval header
  premium/monitor.go
  premium/monitor_test.go
  premium/usage.go
  premium/usage_test.go
Labels: automerge, feat

#1906 feat: Test `MeterUsage` API call on initial setup of client
  go.mod
  premium/usage.go
  premium/usage_test.go
Labels: automerge, feat

#1950 fix: Clean up usage retry logic
  premium/usage.go
  premium/usage_test.go
Labels: automerge, fix
