Repository cloudquery/plugin-sdk, pull requests merged in 2024-03, with the labels that each got.

#1553 fix: MixedBatchWriter should nil the slice instead of zeroing
  writers/mixedbatchwriter/mixedbatchwriter.go
Labels: automerge, fix

#1552 chore: Batch writer benchmarks
  Makefile
  scripts/benchmark-delta/main.go
  writers/writers_test.go
Labels: automerge, ignore-for-release

#1558 feat: Add destination tests for removing a unique constraint
  plugin/testing_write.go
  plugin/testing_write_migrate.go
Labels: automerge, feat

#1560 feat: Enable destinations to completely skip migration that are not supported
  plugin/testing_write.go
  plugin/testing_write_migrate.go
Labels: automerge, feat

#1572 feat: Handle unknown token types when getting team name in usage client
  premium/usage.go
  premium/usage_test.go
Labels: automerge, feat

#1575 chore: Remove writer benchmarks from CI
  Makefile
Labels: automerge, ignore-for-release

#1571 feat: Expose InvocationID to Plugin Client
  examples/simple_plugin/go.mod
  examples/simple_plugin/go.sum
  go.mod
  go.sum
  internal/servers/plugin/v3/plugin.go
  plugin/plugin.go
Labels: automerge, feat
