Repository cloudquery/plugin-sdk, pull requests merged in 2024-04, with the labels that each got.

#1607 chore: Add Test for OTEL Resource Creation
  serve/opentelemetry_test.go
Labels: automerge, ignore-for-release

#1604 feat: Add versioning to state client
  internal/clients/state/v3/state.go
  serve/state_test.go
  state/state.go
Labels: automerge, feat

#1584 feat: Test duplicated primary key insertion
  plugin/testing_write.go
  plugin/testing_write_upsert.go
Labels: automerge

#1632 fix(test): Slice rows properly when reading in tests
  plugin/plugin_read.go
Labels: automerge, fix

#1637 feat: Fill in `CC` and `CXX` environment variables for `package` command
  plugin/plugin_package.go
Labels: automerge, feat

#1643 fix: Fix link to billing page
  premium/monitor.go
Labels: automerge, fix

#1650 feat: Add function to create state client and gRPC backend connection
  internal/clients/state/v3/state.go
  serve/state_test.go
  state/client.go
  state/state.go
Labels: feat
