Repository cloudquery/plugin-sdk, pull requests merged in 2024-01, with the labels that each got.

#1451 feat: Support multiple and/or specific plugin licenses
  plugin/plugin.go
  premium/offline.go
  premium/offline_test.go
  serve/plugin.go
Labels: automerge, feat

#1465 chore: Fix markdown linting
  .github/styles/config/vocabularies/Base/accept.txt
  .github/styles/config/vocabularies/Base/reject.txt
  .github/workflows/lint_markdown.yml
Labels: automerge, ignore-for-release

#1470 feat: Expose special migration paths
  schema/table.go
  schema/table_test.go
Labels: automerge, feat

#1472 fix: Handle unrelated licenses
  serve/plugin.go
Labels: fix

#1477 fix: Eternal recursion in `scalar.MonthInterval`
  scalar/interval.go
Labels: automerge, fix

#1478 fix: Verify `nil` value consistently
  scalar/inet.go
  scalar/inet_test.go
  scalar/interval.go
  scalar/mac.go
Labels: automerge, fix

#1479 feat: Make UUID in `testdata` always deterministic like all other columns
  schema/testdata.go
Labels: automerge, feat

#1480 feat: Expose Migration test for new special case for moving to `_cq_id` as only primary key
  plugin/testing_write.go
  plugin/testing_write_migrate.go
  schema/testdata.go
Labels: automerge, feat

#1473 feat: Add Sync Run API Token Type
  premium/usage.go
Labels: automerge, feat

#1489 fix: When `_cq_id` SyncMigrateMessage not sent
  scheduler/scheduler.go
  scheduler/scheduler_test.go
  schema/table.go
Labels: automerge, fix

#1492 fix: Better build overrides
  plugin/options.go
  plugin/plugin.go
  plugin/plugin_package.go
  serve/package.go
Labels: automerge, fix

#1497 fix: Remove access to parent tests in test suite
  plugin/testing_write.go
  plugin/testing_write_delete.go
Labels: automerge, fix

#1491 feat: Introduce `PrimaryKeyComponent`
  docs/json.go
  scheduler/scheduler_test.go
  schema/arrow.go
  schema/column.go
  schema/doc.go
  schema/resource.go
  schema/table.go
  transformers/struct.go
Labels: automerge, feat

#1503 fix: Handle PrimaryKeyComponents in packaging
  serve/package.go
Labels: automerge, fix
