Repository cloudquery/plugin-sdk, pull requests merged in 2025-01, with the labels that each got.

#2046 feat: Enable storing _cq_client_id.
  examples/simple_plugin/plugin/client.go
  scheduler/queue/worker.go
  scheduler/scheduler_dfs.go
  schema/meta.go
  schema/resource.go
  schema/table.go
Labels: feat

#2049 fix: AWS Marketplace Integration
  premium/usage.go
Labels: automerge, fix

#2063 chore: Update CODEOWNERS
  CODEOWNERS
Labels: ignore-for-release
