Repository cloudquery/plugin-sdk, pull requests merged in 2025-04, with the labels that each got.

#2113 fix: Error if both PKs and PK components are set
  transformers/tables.go
  transformers/tables_test.go
Labels: automerge, fix

#2115 feat: Allow skipping PK components mismatch validation
  schema/table.go
  transformers/tables.go
Labels: automerge, feat

#2125 feat: Add logger to context
  scheduler/queue/worker.go
  scheduler/scheduler_dfs.go
Labels: feat

#2124 feat: Show plugin version in plugin server logs
  plugin/plugin.go
  serve/info.go
  serve/plugin.go
Labels: automerge, feat

#2128 feat: Add transformer to update table description with its table options
  docs/table_options.go
  docs/table_options_test.go
  docs/testdata/schema.json
  docs/testdata/tableoptions.go
  examples/simple_plugin/go.mod
  examples/simple_plugin/go.sum
  go.mod
  go.sum
Labels: automerge, feat

#2131 chore: Double the limit of grpc messages
  examples/simple_plugin/go.mod
  examples/simple_plugin/go.sum
  go.mod
  go.sum
  serve/constants.go
  serve/plugin.go
Labels: ignore-for-release
