Repository cloudquery/plugin-sdk, pull requests merged in 2025-05, with the labels that each got.

#2140 fix: Pass installation ID from env for usage report
  premium/usage.go
Labels: automerge, fix

#2145 chore: Update CLI & Platform docs
  CONTRIBUTING.md
Labels: automerge, ignore-for-release

#2151 chore: Correct sensitive columns validation function name
  plugin/testing_validation.go
Labels: automerge, ignore-for-release

#2154 fix: Flush DeleteRecord messages when batch writer is flushed
  writers/batchwriter/batchwriter.go
Labels: automerge, fix

#2153 fix: Change logic for batch writing to write when batch size is reached, not exceeded
  writers/batchwriter/batchwriter.go
Labels: automerge, fix

#2156 fix: Pass correct value for plugin version
  serve/package.go
Labels: automerge, fix

#2129 feat: Remove reflect methods
  docs/generator.go
  examples/simple_plugin/go.mod
  examples/simple_plugin/go.sum
  go.mod
  go.sum
  plugin/plugin_package.go
  serve/docs.go
  serve/docs_test.go
Labels: automerge, feat

#2163 feat: Improve shard chunking
  scheduler/scheduler.go
  scheduler/scheduler_test.go
Labels: feat

#1978 feat: Add `cloudquery.plugin.path` attribute to traces
  serve/opentelemetry.go
Labels: automerge, feat

#2176 feat: Switch state grpc client to NewClient rather than DialContext
  state/client.go
Labels: automerge, feat, priority merge

#2179 feat: Make SDK FIPS-compliant by using internal SHA1 module
  internal/sha1/byteorder.go
  internal/sha1/sha1.go
  internal/sha1/sha1_test.go
  internal/sha1/sha1block.go
  internal/sha1/sha1block_generic.go
  schema/arrow.go
  schema/arrow_test.go
  schema/resource.go
  schema/testdata.go
Labels: automerge, feat

#2182 fix: Correctly validate backend_options configuration
  state/client.go
Labels: automerge, fix, priority merge
